### ISSUE TITLE
[Compatibility] Cannot load images from Alodokter.com

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#100]
All images from [Alodokter.com](Alodokter.com) cannot be loaded by zerda.

[Alodokter.com](Alodokter.com) is no. 30 of Top 100 ID websites from Alexa

**Comment by mTwTm** [comment]
Images seems to fall into the category of ad trackers. (Pure webview or disabling ad trackers in Settings may fix the problem)

**Comment by harly21** [comment]
This is more related to WebCompat issue, remove UX&VD tag

**Comment by Conjuror** [comment]
On Slack:

> tyu: This issue had UX&VD because we want to discuss about how might we hint user that she should disable speed mode to make things work.

**Comment by Conjuror** [comment]
related to #342

**Comment by Conjuror** [comment]
Close all web copmat issues to #342.
