### ISSUE TITLE
Play Store icon has white background, expected to be translucent in Play Store animation

### ISSUE THREAD

**Issue by mcomella** [mozilla-tw/Zerda#1003]
I wonder if it'd cause issues elsewhere too.

Here's a [video of the animation](https://drive.google.com/file/d/0B1U7M7wyeYhFSjJkby11ZHdYY1k/view?usp=sharing).

Here's a screenshot of the video:
![screen shot 2017-09-27 at 11 24 50](https://user-images.githubusercontent.com/759372/30930458-9e940146-a376-11e7-9ad0-141365850c5f.png)

**Comment by Conjuror** [comment]
Won't block RC but suggest to fix before release.

**Comment by elin-moco** [comment]
Hi, 

I've also updated the icon with transparent background.
Should be OK now.

**Comment by chianger** [comment]
QAWanted for verify then.
