### ISSUE TITLE
Screenshot animation, with success check mark, played 3 times

### ISSUE THREAD

**Issue by mcomella** [mozilla-tw/Zerda#1004]
See [the attached video](https://drive.google.com/open?id=0B1U7M7wyeYhFWS1RUHktc0Z2Q00).

I have no STR. This happened on my GS5 (a slower device) the first time I opened Youtube but not the first time I took a screenshot. I deleted all my existing screenshots before taking this screenshot.

**Comment by Conjuror** [comment]
This is know issue and should be fixed. Close as invalid
