### ISSUE TITLE
Screenshot animation overlaps success snackbar, makes time to hit "Share" minimal

### ISSUE THREAD

**Issue by mcomella** [mozilla-tw/Zerda#1005]
See [the attached video](https://drive.google.com/file/d/0B1U7M7wyeYhFWS1RUHktc0Z2Q00/view?usp=sharing).

I only have a split second to hit the "SHARE" option in the displayed Snackbar, which seems unreasonable. Also, fwiw the Snackbar feels a little redundant to the check mark animation.

I filed #1004 for the repeating success checkmark animation.

**Comment by Conjuror** [comment]
We knew this issue and change the design from snackbar to toast. Therefore, no "Share" will be there on build 1374 or later. Close as invalid issue and dup it later :)

**Comment by Conjuror** [comment]
dup #833
