### ISSUE TITLE
[Smoke Test] Tapping item menu when it's moving makes the menu pop up on the top and no snack bar

### ISSUE THREAD

**Issue by dakaizou** [mozilla-tw/Zerda#1006]
STR:
1. Download at least three item 
2. Open Downloads panel
3. As soon as deleting the item, tap on the other item menu
4. Menu pops up at the top
5. Tap on Delete file of the menu on the top
6. Repeat step 3 to 5

See [recording](https://drive.google.com/file/d/0B0uVZlaHN366QXRQZzI3TkpKajQ/view?usp=sharing)

Build: 1374
DuT: Samsung

**Comment by mTwTm** [comment]
This bug will track: The menu pops up on the top
No snack bar is (sort of) tracked in #1017 
And maybe wrong item is deleted is tracked in #1010

**Comment by mTwTm** [comment]
To me only #1017 and maybe #1010 requires uplift, but not this one about context menu position. I'll change the label after making sure triagers agree.

**Comment by chianger** [comment]
since #1017, #1010, and #1007 are merged, the remained symptom is only the pop-up position being unexpected which should be P2.

**Comment by dakaizou** [comment]
verified in build 1512
