### ISSUE TITLE
[Smoke Test] No snack bar when saving the same file to sdcard 

### ISSUE THREAD

**Issue by dakaizou** [mozilla-tw/Zerda#1007]
as title, same behavior with #970 while the file is saved successfully.

Build: 1378
DuT: Samsung

**Comment by mTwTm** [comment]
There will be duplicate items, but when we delete one of them all of them becomes invalid. After discussed with UX, we shall still send the snackbar and move the existing item to the top of the panel.

**Comment by mTwTm** [comment]
Fixed in #1018

**Comment by dakaizou** [comment]
verified in build 1647
