### ISSUE TITLE
Hide fab when user taps the input box

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/Zerda#101]
Example:
![screenshot_20170801-170433](https://user-images.githubusercontent.com/6755074/28820922-06f88012-76e6-11e7-8a43-0da2b6549e0f.png)

Or maybe we can just don't have FABs pushed by the keyboard. This is the behavior of Focus.

Blocks: #111

**Comment by idiotmax** [comment]
Design changed. Close
