### ISSUE TITLE
Download is listed as finished but it is actually still ongoing moving to sdcard

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/Zerda#1014]
Originally filed in #1006, there's also a recording there.
We've moved the file to sdcard but the panel is not updated so there is a "File not found"
See log:

09-28 12:00:56.911 12121-12121/org.mozilla.rocket.debug.tyu E/mTwTm: bind item at 0 with downloadId 741
09-28 12:00:56.921 12121-12121/org.mozilla.rocket.debug.tyu E/mTwTm: bind item at 1 with downloadId 740
09-28 12:00:56.931 12121-12121/org.mozilla.rocket.debug.tyu E/mTwTm: bind item at 2 with downloadId 738
09-28 12:00:56.941 12121-12121/org.mozilla.rocket.debug.tyu E/mTwTm: bind item at 3 with downloadId 736
09-28 12:00:56.951 12121-12121/org.mozilla.rocket.debug.tyu E/mTwTm: bind item at 4 with downloadId 734
09-28 12:00:57.101 12121-12121/org.mozilla.rocket.debug.tyu E/mTwTm: bind item at 0 with downloadId 741
09-28 12:00:57.101 12121-12121/org.mozilla.rocket.debug.tyu E/mTwTm: bind item at 1 with downloadId 740
09-28 12:00:57.101 12121-12121/org.mozilla.rocket.debug.tyu E/mTwTm: bind item at 2 with downloadId 738
09-28 12:00:57.111 12121-12121/org.mozilla.rocket.debug.tyu E/mTwTm: bind item at 3 with downloadId 736
09-28 12:00:57.111 12121-12121/org.mozilla.rocket.debug.tyu E/mTwTm: bind item at 4 with downloadId 734
09-28 12:01:21.911 12121-12121/org.mozilla.rocket.debug.tyu E/mTwTm: Delete item at 0 with downloadId 741
09-28 12:01:22.961 12121-12121/org.mozilla.rocket.debug.tyu E/mTwTm: Delete item at 0 with downloadId 741
09-28 12:01:24.381 12121-12121/org.mozilla.rocket.debug.tyu E/mTwTm: Delete item at 0 with downloadId 741
09-28 12:01:25.251 12121-12121/org.mozilla.rocket.debug.tyu E/mTwTm: Delete item at 0 with downloadId 741

**Comment by mTwTm** [comment]
I think we can solve this by keeping it in `downloading` state when it is being moved.

**Comment by mTwTm** [comment]
Fixed in #1018

**Comment by dakaizou** [comment]
verified in build 1512
