### ISSUE TITLE
[Function] File chooser for uploading files to website

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/Zerda#102]
acceptance criteria:
    able to handle File chooser

**Comment by walkingice** [comment]
In #376 I implemented the uploading function, used these two site for testing and works
* https://encodable.com/uploaddemo/
* https://fineuploader.com/demos.html

Unfortunately it doesn't work on send.firefox.com

If you think it is necessary, please file a new bug to track it.

**Comment by Conjuror** [comment]
Thanks for the great work. Yes, the issue should still be traced. Issue #394 is filed for it. 👍

**Comment by Conjuror** [comment]
Verified on uploading files. Strill trace #394 for progress.
