### ISSUE TITLE
visit an unavailable page several times will put it to Top Sites (RC2)

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#1026]
STR:

1. Visit http://wesley.huang
2. tap on "TRY AGAIN" several time
3. Observe Top Sites

Build 1412 RC1
DuT: Redmi

**Comment by Conjuror** [comment]
related to #824

**Comment by Conjuror** [comment]
suggest not to add the counter while failed to load the page.

**Comment by chianger** [comment]
@joseph-yar possible to fix this by next Monday? We're planning to build RC2 next Tuesday.

**Comment by mTwTm** [comment]
10-01 14:18:19.915 16096-16096/org.mozilla.zerda.debug.tyu E/mTwTm: Failing: http://wesley.huang/
10-01 14:18:19.915 16096-16096/org.mozilla.zerda.debug.tyu E/mTwTm: url: http://wesley.huang/
10-01 14:18:20.974 16096-16096/org.mozilla.zerda.debug.tyu E/mTwTm: Failing: http://wesley.huang/
10-01 14:18:20.974 16096-16096/org.mozilla.zerda.debug.tyu E/mTwTm: url: http://wesley.huang/
10-01 14:18:20.988 16096-16096/org.mozilla.zerda.debug.tyu E/mTwTm: Failing: null
10-01 14:18:20.988 16096-16096/org.mozilla.zerda.debug.tyu E/mTwTm: url: http://wesley.huang/
10-01 14:18:21.020 16096-16096/org.mozilla.zerda.debug.tyu E/mTwTm: "null".equals(errorPage) = true
10-01 14:18:31.630 16096-16096/org.mozilla.zerda.debug.tyu E/mTwTm: Failing: http://wesley.huang/
10-01 14:18:31.630 16096-16096/org.mozilla.zerda.debug.tyu E/mTwTm: url: http://wesley.huang/
10-01 14:18:31.651 16096-16096/org.mozilla.zerda.debug.tyu E/mTwTm: Failing: null
10-01 14:18:31.651 16096-16096/org.mozilla.zerda.debug.tyu E/mTwTm: url: http://wesley.huang/
10-01 14:18:31.686 16096-16096/org.mozilla.zerda.debug.tyu E/mTwTm: "null".equals(errorPage) = false
10-01 14:18:35.355 16096-16096/org.mozilla.zerda.debug.tyu E/mTwTm: Failing: http://wesley.huang/
10-01 14:18:35.359 16096-16096/org.mozilla.zerda.debug.tyu E/mTwTm: url: http://wesley.huang/
10-01 14:18:35.368 16096-16096/org.mozilla.zerda.debug.tyu E/mTwTm: Failing: null
10-01 14:18:35.368 16096-16096/org.mozilla.zerda.debug.tyu E/mTwTm: url: http://wesley.huang/
10-01 14:18:35.394 16096-16096/org.mozilla.zerda.debug.tyu E/mTwTm: "null".equals(errorPage) = true
10-01 14:18:35.398 16096-16096/org.mozilla.zerda.debug.tyu E/mTwTm: Failing: null
10-01 14:18:35.398 16096-16096/org.mozilla.zerda.debug.tyu E/mTwTm: url: data:text/html;charset=utf-8;base64,
10-01 14:18:35.411 16096-16096/org.mozilla.zerda.debug.tyu E/mTwTm: "null".equals(errorPage) = false
10-01 14:18:36.501 16096-16096/org.mozilla.zerda.debug.tyu E/mTwTm: Failing: http://wesley.huang/
10-01 14:18:36.501 16096-16096/org.mozilla.zerda.debug.tyu E/mTwTm: url: http://wesley.huang/
10-01 14:18:37.388 16096-16096/org.mozilla.zerda.debug.tyu E/mTwTm: Failing: http://wesley.huang/
10-01 14:18:37.389 16096-16096/org.mozilla.zerda.debug.tyu E/mTwTm: url: http://wesley.huang/
10-01 14:18:37.404 16096-16096/org.mozilla.zerda.debug.tyu E/mTwTm: Failing: null
10-01 14:18:37.404 16096-16096/org.mozilla.zerda.debug.tyu E/mTwTm: url: http://wesley.huang/
10-01 14:18:37.417 16096-16096/org.mozilla.zerda.debug.tyu E/mTwTm: "null".equals(errorPage) = true
10-01 14:18:38.179 16096-16096/org.mozilla.zerda.debug.tyu E/mTwTm: Failing: http://wesley.huang/
10-01 14:18:38.180 16096-16096/org.mozilla.zerda.debug.tyu E/mTwTm: url: http://wesley.huang/
10-01 14:18:38.189 16096-16096/org.mozilla.zerda.debug.tyu E/mTwTm: Failing: null
10-01 14:18:38.189 16096-16096/org.mozilla.zerda.debug.tyu E/mTwTm: url: http://wesley.huang/
10-01 14:18:38.205 16096-16096/org.mozilla.zerda.debug.tyu E/mTwTm: "null".equals(errorPage) = true
10-01 14:18:38.903 16096-16096/org.mozilla.zerda.debug.tyu E/mTwTm: Failing: http://wesley.huang/
10-01 14:18:38.903 16096-16096/org.mozilla.zerda.debug.tyu E/mTwTm: url: http://wesley.huang/
10-01 14:18:38.925 16096-16096/org.mozilla.zerda.debug.tyu E/mTwTm: Failing: null
10-01 14:18:38.925 16096-16096/org.mozilla.zerda.debug.tyu E/mTwTm: url: http://wesley.huang/
10-01 14:18:38.939 16096-16096/org.mozilla.zerda.debug.tyu E/mTwTm: "null".equals(errorPage) = true
10-01 14:18:38.956 16096-16096/org.mozilla.zerda.debug.tyu E/mTwTm: Failing: null
10-01 14:18:38.956 16096-16096/org.mozilla.zerda.debug.tyu E/mTwTm: url: data:text/html;charset=utf-8;base64,
10-01 14:18:38.972 16096-16096/org.mozilla.zerda.debug.tyu E/mTwTm: "null".equals(errorPage) = false
10-01 14:18:39.575 16096-16096/org.mozilla.zerda.debug.tyu E/mTwTm: Failing: http://wesley.huang/
10-01 14:18:39.575 16096-16096/org.mozilla.zerda.debug.tyu E/mTwTm: url: http://wesley.huang/

**Comment by mTwTm** [comment]
10-01 14:54:34.580 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageStarted, update url to null
10-01 14:54:34.620 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageFinished < http://wesley.huang/ >
10-01 14:54:34.620 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: failingUrl is < http://wesley.huang/ > should insert = false
10-01 14:54:34.641 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageStarted, update url to null
10-01 14:54:34.661 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageFinished < http://wesley.huang/ >
10-01 14:54:34.684 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageFinished < http://wesley.huang/ >
10-01 14:54:34.685 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: Page has mozillaErrorPage tag = true
10-01 14:54:34.698 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: Page has mozillaErrorPage tag = true
10-01 14:54:43.941 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageStarted, update url to null
10-01 14:54:43.989 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageFinished < http://wesley.huang/ >
10-01 14:54:43.989 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: failingUrl is < http://wesley.huang/ > should insert = false
10-01 14:54:43.993 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageStarted, update url to null
10-01 14:54:44.008 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageFinished < http://wesley.huang/ >
10-01 14:54:44.023 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: Page has mozillaErrorPage tag = true
10-01 14:54:44.040 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageFinished < http://wesley.huang/ >
10-01 14:54:44.057 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: Page has mozillaErrorPage tag = true
10-01 14:54:46.414 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageStarted, update url to null
10-01 14:54:46.456 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageFinished < http://wesley.huang/ >
10-01 14:54:46.456 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: failingUrl is < http://wesley.huang/ > should insert = false
10-01 14:54:46.466 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageStarted, update url to null
10-01 14:54:46.475 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageFinished < http://wesley.huang/ >
10-01 14:54:46.497 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: Page has mozillaErrorPage tag = false
10-01 14:54:46.505 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageFinished < http://wesley.huang/ >
10-01 14:54:46.515 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: Page has mozillaErrorPage tag = true
10-01 14:55:01.147 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageStarted, update url to null
10-01 14:55:01.198 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageFinished < http://wesley.huang/ >
10-01 14:55:01.198 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: failingUrl is < http://wesley.huang/ > should insert = false
10-01 14:55:01.208 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageStarted, update url to null
10-01 14:55:01.216 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageFinished < http://wesley.huang/ >
10-01 14:55:01.228 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: Page has mozillaErrorPage tag = true
10-01 14:55:01.230 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageFinished < http://wesley.huang/ >
10-01 14:55:01.244 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: Page has mozillaErrorPage tag = true
10-01 14:55:03.175 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageStarted, update url to null
10-01 14:55:03.194 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageFinished < http://wesley.huang/ >
10-01 14:55:03.194 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: failingUrl is < http://wesley.huang/ > should insert = false
10-01 14:55:03.209 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageStarted, update url to null
10-01 14:55:03.221 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageFinished < http://wesley.huang/ >
10-01 14:55:03.239 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageFinished < http://wesley.huang/ >
10-01 14:55:03.240 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: Page has mozillaErrorPage tag = true
10-01 14:55:03.251 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: Page has mozillaErrorPage tag = true
10-01 14:55:04.339 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageStarted, update url to null
10-01 14:55:04.353 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageFinished < http://wesley.huang/ >
10-01 14:55:04.353 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: failingUrl is < http://wesley.huang/ > should insert = false
10-01 14:55:04.365 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageStarted, update url to null
10-01 14:55:04.376 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageFinished < http://wesley.huang/ >
10-01 14:55:04.389 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: Page has mozillaErrorPage tag = false
10-01 14:55:04.423 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageFinished < http://wesley.huang/ >
10-01 14:55:04.439 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: Page has mozillaErrorPage tag = true
10-01 14:55:12.196 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageStarted, update url to null
10-01 14:55:12.211 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageFinished < http://wesley.huang/ >
10-01 14:55:12.211 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: failingUrl is < http://wesley.huang/ > should insert = false
10-01 14:55:12.226 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageStarted, update url to null
10-01 14:55:12.229 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageFinished < http://wesley.huang/ >
10-01 14:55:12.247 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: Page has mozillaErrorPage tag = true
10-01 14:55:12.248 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageFinished < http://wesley.huang/ >
10-01 14:55:12.264 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: Page has mozillaErrorPage tag = true
10-01 14:55:13.785 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageStarted, update url to null
10-01 14:55:13.804 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageFinished < http://wesley.huang/ >
10-01 14:55:13.804 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: failingUrl is < http://wesley.huang/ > should insert = false
10-01 14:55:13.814 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageStarted, update url to null
10-01 14:55:13.821 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageFinished < http://wesley.huang/ >
10-01 14:55:13.836 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: Page has mozillaErrorPage tag = false
10-01 14:55:13.855 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageFinished < http://wesley.huang/ >
10-01 14:55:13.873 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: Page has mozillaErrorPage tag = true
10-01 14:55:15.182 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageStarted, update url to null
10-01 14:55:15.196 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageFinished < http://wesley.huang/ >
10-01 14:55:15.196 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: failingUrl is < http://wesley.huang/ > should insert = false
10-01 14:55:15.202 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageStarted, update url to null
10-01 14:55:15.242 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageFinished < http://wesley.huang/ >
10-01 14:55:15.260 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: Page has mozillaErrorPage tag = true
10-01 14:55:15.874 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageStarted, update url to null
10-01 14:55:15.907 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageFinished < http://wesley.huang/ >
10-01 14:55:15.907 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: failingUrl is < http://wesley.huang/ > should insert = false
10-01 14:55:15.913 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageStarted, update url to null
10-01 14:55:15.932 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageFinished < http://wesley.huang/ >
10-01 14:55:15.944 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: Page has mozillaErrorPage tag = true
10-01 14:55:15.961 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageFinished < http://wesley.huang/ >
10-01 14:55:15.976 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: Page has mozillaErrorPage tag = true
10-01 14:55:16.600 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageStarted, update url to null
10-01 14:55:16.621 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageFinished < http://wesley.huang/ >
10-01 14:55:16.621 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: failingUrl is < http://wesley.huang/ > should insert = false
10-01 14:55:16.633 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageStarted, update url to null
10-01 14:55:16.636 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageFinished < http://wesley.huang/ >
10-01 14:55:16.655 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: Page has mozillaErrorPage tag = true
10-01 14:55:16.668 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageFinished < http://wesley.huang/ >
10-01 14:55:16.686 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: Page has mozillaErrorPage tag = true
10-01 14:55:17.268 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageStarted, update url to null
10-01 14:55:17.298 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageFinished < http://wesley.huang/ >
10-01 14:55:17.298 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: failingUrl is < http://wesley.huang/ > should insert = false
10-01 14:55:17.306 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageStarted, update url to null
10-01 14:55:17.309 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageFinished < http://wesley.huang/ >
10-01 14:55:17.331 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: Page has mozillaErrorPage tag = false
10-01 14:55:17.335 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageFinished < http://wesley.huang/ >
10-01 14:55:17.348 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: Page has mozillaErrorPage tag = true
10-01 14:55:17.952 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageStarted, update url to null
10-01 14:55:17.967 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageFinished < http://wesley.huang/ >
10-01 14:55:17.967 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: failingUrl is < http://wesley.huang/ > should insert = false
10-01 14:55:17.973 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageStarted, update url to null
10-01 14:55:17.985 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageFinished < http://wesley.huang/ >
10-01 14:55:18.001 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: Page has mozillaErrorPage tag = true
10-01 14:55:18.019 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageFinished < http://wesley.huang/ >
10-01 14:55:18.034 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: Page has mozillaErrorPage tag = true
10-01 14:55:19.004 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageStarted, update url to null
10-01 14:55:19.045 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageFinished < http://wesley.huang/ >
10-01 14:55:19.045 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: failingUrl is < http://wesley.huang/ > should insert = false
10-01 14:55:19.050 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageStarted, update url to null
10-01 14:55:19.051 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageFinished < http://wesley.huang/ >
10-01 14:55:19.070 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: Page has mozillaErrorPage tag = false
10-01 14:55:19.087 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: onPageFinished < http://wesley.huang/ >
10-01 14:55:19.103 6672-6672/org.mozilla.zerda.debug.tyu E/mTwTm: Page has mozillaErrorPage tag = true

The assumption of onPageFinished is returned when page is fully loaded is false.

**Comment by mTwTm** [comment]
evaluateJavascript("(function() { return document.getElementsByTagName('html')[0].innerHTML; })();",
                new ValueCallback<String>() {
                    @Override
                    public void onReceiveValue(String html) {
                        Log.e("mTwTm", html);

                        Site site = new Site();
                        site.setUrl(url);
                        site.setTitle(getTitle());
                        site.setLastViewTimestamp(System.currentTimeMillis());
                        site.setFavIcon(FavIconUtils.getInitialBitmap(getResources(), null, FavIconUtils.getRepresentativeCharacter(url)));
                        BrowsingHistoryManager.getInstance().insert(site, null);
                    }
                });

might return null, which means even in onPageFinished(), null may be returned rather than errorpage, which returns "null" in return document.getElementById('mozillaErrorPage');

**Comment by dakaizou** [comment]
verified in build 1455
