### ISSUE TITLE
[SUMO] Support page links to a blank one (NO Code change on APK needed)

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/Zerda#1036]
STR:
1. Go to Settings > About , tap on the 'Support' link
Actual result:
Content is empty 
![screenshot_20171002-144931](https://user-images.githubusercontent.com/9859809/31066732-9274aa0a-a781-11e7-82ab-1efb1389169a.png)

Note:
Check with Ben that we did have the correct format as below.
https://support.mozilla.org/1/mobile/%VERSION%/%OS%/%LOCALE%/rocket-help

Expect result:
Should page redirected to the overview page
https://support.mozilla.org/en-US/kb/get-started-firefox-rocket

**Comment by dakaizou** [comment]
verified in build 1455
