### ISSUE TITLE
[META] Top Sites

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#1037]
Follow up of #815 

We'll need to discuss Top implementation.

**Comment by chianger** [comment]
#915 is being tracked under P1. If there's no other relevant bug let's close this meta

**Comment by FlyTori** [comment]
UX proposal 
https://docs.google.com/document/d/1Ow5nUSdLI22jdCeD3F4HsHPs571DtEMZNt66DJgTQn0/edit

**Comment by chianger** [comment]
enahncment design tracked under #1090
