### ISSUE TITLE
[css spritesheet] firefox focus for android, firefox focus for ios, firefox rocket icon not displaying in SUMO AAQ, rest of the icons are clipped/cut off (CSS overflow?) on the top or bottom

### ISSUE THREAD

**Issue by rtanglao** [mozilla-tw/Zerda#1045]
**Steps to reproduce:**

1. On any of the non gecko based firefox mobile browser products (firefox focus for android, firefox focus for android, firefox focus for ios, firefox rocket), go to support.mozilla.org
1. tap on "Ask a question"

**Expected Result:**

1. All the Firefox  icons show  up correctly on the top

**Actual Result:**

1. icons are clipped/cut off (is this a CSS overflow issue?!?!) ! 
See screenshots:
* https://flic.kr/p/YZNt8b (latest rocket nightly) **see [screenshot1]**
* https://flic.kr/p/Z2g7qL (focus for android) 
* https://flic.kr/p/YFpzfu (firefox for ios)
* https://flic.kr/p/Y3ZEAr (focus for ios)

May be related to [bug 1404792](https://bugzilla.mozilla.org/show_bug.cgi?id=1404792)

**[screenshot1] taken on note8, android 7**

![37410085676_c12bf4deb2_o](https://user-images.githubusercontent.com/45195/31098318-071cdb4e-a777-11e7-85bf-92be84beb319.jpg)

**Comment by rtanglao** [comment]
![37426600572_70154a6b4b_o](https://user-images.githubusercontent.com/45195/31098239-cddaafbe-a776-11e7-80ad-7f1eeeebee45.jpg)

**Comment by rtanglao** [comment]
This is not an issue with Firefox for Android 55.0.2 so maybe this is Chromium-based-browser specific?

**Comment by Conjuror** [comment]
> This is not an issue with Firefox for Android 55.0.2 so maybe this is Chromium-based-browser specific?

I think so. Same thing happens on Chrome and UC browser. It should be an issue for webview.

**Comment by rtanglao** [comment]
@Conjuror we're not going to get a webview update before launch on october 9!
Therefore I guess Ishould file a bugzilla bug to get the support.mozilla.org developers (aka "kitsune" developers) to workaround this problem in chromium based browsers right? (perhaps with some sort of kitsune CSS change to the CSS sprites so it will work on Fennec and Chrome based browsers?!? I don't know since I know nothing about CSS Sprites)

**Comment by rtanglao** [comment]
i filed the following bug to see if there's a Kitsune workaround:

https://bugzilla.mozilla.org/show_bug.cgi?id=1405545

**Comment by rtanglao** [comment]
fixed by :giorgos !!!! thanks Giorgos!

**Comment by rtanglao** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1405545#c5
