### ISSUE TITLE
Menu panel layout adjustment (Indonesian)  (RC3)

### ISSUE THREAD

**Issue by FlyTori** [mozilla-tw/Zerda#1049]
Some items on the menu panel have two lines after translated to Indonesian. Need to adjust the layout to make it look nicer.

![indonesia-menu](https://user-images.githubusercontent.com/3325366/31113430-e4ad58dc-a7de-11e7-99c9-afde86c85404.png)

**Comment by mTwTm** [comment]
Should also add padding for this. 
![4-1](https://user-images.githubusercontent.com/6755074/31118055-a483f268-a85e-11e7-81c4-55af28972786.png)

**Comment by dakaizou** [comment]
verified in build 1512
