### ISSUE TITLE
"OPEN" in the snack bar of files just downloaded can't work (RC3)

### ISSUE THREAD

**Issue by cssjh** [mozilla-tw/Zerda#1051]
**STR**
1. Set save files to SD card
2. Download a file
3. When the download is finished, tap "OPEN" in the snack bar -> the file won't open

**DuT:** Samsung J7 Prime
**Build:** 1437 RC2

**Comment by cssjh** [comment]
oops so awkward...:P
@chianger thanks for correcting!

**Comment by dakaizou** [comment]
verified in build 1512
