### ISSUE TITLE
"Downloading" item is inserted into wrong position

### ISSUE THREAD

**Issue by WeiWW** [mozilla-tw/Zerda#1054]
In downloading, when open download panel open before the item inserted in, it will be add in the end. But open it again, it will be at first.

**Comment by mTwTm** [comment]
STR:

1. Click a link that would download automatically
2. Open download panel before download starts
3. When download started, an item will be added at the end of the list
Expected in step 3: Should be added at the top of the list.

Note: if we opens the download after download started / or close the panel and re-open, we will not see the symptom.

**Comment by dakaizou** [comment]
verified in build 1512
