### ISSUE TITLE
APK export aplha/beta test?

### ISSUE THREAD

**Issue by petrk94** [mozilla-tw/Zerda#1058]
Hello,
I would like to know whether there exist already a alpha build of Browser as APK file for testing?
Or whether someone can export a apk file.
Thanks

**Comment by joechengla** [comment]
thanks for the feedback. APKs will be made available on github soon when we start opening up

**Comment by petrk94** [comment]
@joechengla looking forward too :)

**Comment by Conjuror** [comment]
Since shipping apk is planned and there's no action item for the issue. Close as invalid.
