### ISSUE TITLE
prompt requested site permisison

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/Zerda#11]
acceptance criteria:
when website requests, prompt the dialog to end user for accepting or denying (not functioning).

**Comment by mTwTm** [comment]
@idiotmax is Ben already on this?

**Comment by walkingice** [comment]
change assignee to Ben

**Comment by chianger** [comment]
seen it worked on latest daily build now

**Comment by Conjuror** [comment]
worked in build 121
