### ISSUE TITLE
FAB should hide during playing video

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#110]
FAB should hide during playing video, such as YouTube

**Comment by mTwTm** [comment]
Can't reproduce, possibly affected by #119

**Comment by mTwTm** [comment]
^ If this issue is about full screen mode

**Comment by Conjuror** [comment]
I think this is for full screen mode. During full screen mode, FAB won't disappear.

**Comment by chianger** [comment]
No FAB now let's close it.

**Comment by dakaizou** [comment]
Invalid
