### ISSUE TITLE
Unable to switch to fullscreen mode in Youtube; focus has same issue

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#117]
as title

**Comment by mTwTm** [comment]
Focus issue is here https://github.com/mozilla-mobile/focus-android/issues/855
Facebook app is suffering the same symptom, and looks like people in Chromium team are already looking into this.

**Comment by Conjuror** [comment]
Checked on Samsung J7. This shouldn't be an issue anymore. Close it for now.
