### ISSUE TITLE
Unable to use OAuth login

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#120]
> Dogfooding comment:
> "cannot login to instragram using Facebook login (already logged into facebook)
> Quora is the same, but we can login with Google (interesting!)"

as title

**Comment by chianger** [comment]
added to sprint6 to investigate first.

**Comment by walkingice** [comment]
compare to other browser, if we add this line, Instagram oauth login seems start working

```java
CookieManager.getInstance().setAcceptThirdPartyCookies(webkitView, true);
```

Unfortunately, the method is involved since API 23 :-/

**Comment by mTwTm** [comment]
If we're using this, we should probably mention this in the security review too.

**Comment by Ben-YPLai** [comment]
Apps that target KITKAT or below default to allowing third party cookies. Apps targeting LOLLIPOP or later default to disallowing third party cookies.

**Comment by cssjh** [comment]
**Verified** on 1050.
