### ISSUE TITLE
The download panel is not refreshed once a download is complete

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/Zerda#125]
STR:

1. Do a download
2. Open download panel, which has "Running..."

Actual result
The download is finished, but the status is not updated, it's still "Running..."

Expected result
The status change to download time and size.

**Comment by mTwTm** [comment]
Propose to triage as P3 bug

**Comment by chianger** [comment]
The status confuses user so we're setting P1.

**Comment by dakaizou** [comment]
Testing link: [coverr.co](http://www.coverr.co/s3/mp4/Mobile-Games.mp4)

**Comment by dakaizou** [comment]
Downloading now disappears after finishing as it should be, but paused and downloading still not working
Build: 1050
DuT Advan, Oppo

**Comment by mTwTm** [comment]
Fixed in #810

**Comment by dakaizou** [comment]
verified in build 1307
