### ISSUE TITLE
Back key won't be able to back to home screen

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#130]
STR:
1. Launch Zerda
2. Tap on any website (i.e. from search button or from top sites)
3. Tap Settings button
4. Tap back button
Expected Result:
4. Back to home screen
Actual Result:
4. Nothing

If using system back key, it works perfectly. Only back key from settings menu won't work.

**Comment by chianger** [comment]
From latest design, we'll remove this back key from Zerda's menu UI. User can use system's back.

**Comment by dakaizou** [comment]
Verified in build 540
