### ISSUE TITLE
back key should work even we have home screen in track

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#131]
While browsing, back key should work to visit previous web page. If we attempt to visit home screen during browsing, it should be recorded as well.

i.e,
A→B→C→(software home key) Top Sites→D→E
press back key will visit following pages in order:
D→Top Sites→C→B→A

**Comment by mTwTm** [comment]
This can be even more complex when "pages open through other apps" get into play. Does the history reset or not under such situation should be discussed too.

**Comment by Conjuror** [comment]
Verified on build 382.
