### ISSUE TITLE
Block custom tab implementation

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/Zerda#133]
We need to at least cut this from the entry point to avoid unexpected behaviors.

**Comment by Conjuror** [comment]
from dogfooding
> Open links from Gmail - Cannot interact with URL and URL bar is colored
> Settings-Clear browsing data-"Form history"
> "Settings-Clear browsing data" default enabled: Browsing history, Search history, Form history,  Cookies, Cache

**Comment by Conjuror** [comment]
Verified on build 439
