### ISSUE TITLE
Video at incorrect position while playing in fullscreen mode

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#134]
STR:
1. go to video page (i.e., [despacito](https://vimeo.com/204469177)
2. scroll the page down a little bit
3. Hit the play button
Expected result:
3. video display in the mid of screen w/ fullscreen mode
Actual result:
3. a white banner at the top of the page

Reproduce rate: 95%

**Comment by Conjuror** [comment]
https://drive.google.com/a/mozilla.com/file/d/0B11T5xYLeXAOYlFaLTFsa1R1ams/view?usp=sharing

**Comment by dakaizou** [comment]
Verified in build 623
DuT: Samsung, advan, andromax

**Comment by dakaizou** [comment]
Remove QAwanted since verified
