### ISSUE TITLE
[Function] Menu->Browsing History

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/Zerda#14]
acceptance criteria:
1. able to display the history panel, and scroll up/down to navigate. Historical links are sorted by time of visit.
2. able to open link from history panel
3. able to clear history one by one 
4. able to clear history all at once

**Comment by chianger** [comment]
for the record, we trade #34 to sprint#3 and this one goes to sprint#4

**Comment by mTwTm** [comment]
I think we can close this one :)

**Comment by Conjuror** [comment]
Verified in build 357
