### ISSUE TITLE
[Download] Download should have a cancel button

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#151]
Currently, only Android 7.0 and above provide cancel button in system tray. We'll need a cancel mechanism for Android 5.x and 6.x.

**Comment by mTwTm** [comment]
FYI: When implementing this, I suppose we do not need to differentiate between versions, simply add a cancel option to the context menu.

**Comment by Conjuror** [comment]
As the major target is to give the accessibility to stop a download, I am totally agree to keep in simple for now.

**Comment by Conjuror** [comment]
good in build 972
