### ISSUE TITLE
Download panel is not full screen on longer devices

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/Zerda#159]
We're only allocating 600dp for the Recyclerview, so on pixel it will not reach the top when expanded

**Comment by chianger** [comment]
likely resolved

**Comment by chianger** [comment]
can reproduce on z3c  still today.

**Comment by Conjuror** [comment]
related to #284

**Comment by mTwTm** [comment]
This issue is already invalid (We are already giving full screen), track #284 for another similar issue.
