### ISSUE TITLE
The download list is cropped when list exceeds one page.

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/Zerda#165]
![screenshot_20170808-163204](https://user-images.githubusercontent.com/6755074/29063505-b9f6c422-7c58-11e7-9580-1d8909bb3d3e.png)

This list cannot scroll down further but the last item is covered.

**Comment by mTwTm** [comment]
Fixed in #211

**Comment by Conjuror** [comment]
Verified in build 382
