### ISSUE TITLE
[dogfooding] Google search results map. Click "Call" will show exit private browsing?

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#167]
as title

**Comment by chianger** [comment]
that is legacy message from Focus. For zerda we don't need such message.

**Comment by Conjuror** [comment]
other example: Google Map navigation: You can leave Zerda preview to open this link in Google Play Services

**Comment by chianger** [comment]
zerda doesn't need the dialog

**Comment by cssjh** [comment]
**Verified** in build 636
