### ISSUE TITLE
[dogfooding] unable to disable track protection

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#169]
進入https://pkget.com 會出現不支援私密瀏覽的dialog 網頁無法使用 不能抓怪了><

**Comment by mTwTm** [comment]
Duplicate to #53

**Comment by dakaizou** [comment]
Invalid

**Comment by mTwTm** [comment]
I think this should still be valid as the title is `unable to disable track protection` and we still don't have speed mode UI glued yet.
