### ISSUE TITLE
[dogfooding] no response for the very first time of clicking

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#170]
as title
http://www.freeplaymusic.com/volumedetail.aspx?volume=53382"

**Comment by Conjuror** [comment]
All web compat are tracked with #342. Since it's not Top 100 ID sites, keep it alive and track separately.

**Comment by Conjuror** [comment]
[WebCompat] Engineering to take a look in Sprint 6

**Comment by Conjuror** [comment]
#454 to track

**Comment by chianger** [comment]
Zoom in and click on the "play" button should be able to bring up the play panel.
