### ISSUE TITLE
[dogfooding] cannot load testpilot website

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#171]
打不開testpilot.firefox.com XD

**Comment by chianger** [comment]
focus and chrome can load the page.

**Comment by Conjuror** [comment]
All web compat are tracked with #342. Since it's not Top 100 ID sites, keep it alive and track separately.

**Comment by idiotmax** [comment]
Fixed by #434

**Comment by Conjuror** [comment]
good on build 592.
