### ISSUE TITLE
[dogfooding] search suggestion performance

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#172]
as title. Be noted current version is for demo purpose.

**Comment by chianger** [comment]
current build is hardcoded, so we should revisit this when we have that feature ready.

**Comment by walkingice** [comment]
yes, I added 2 seconds delay in purpose to pretend we are in terrible network. Then UX can decide whether to deal with it or not.
https://github.com/mozilla-tw/Zerda/commit/692f8a2be1b37bfc719da019370e2a56f7556643#diff-50f8e3534d7775723fd8d5030d87054fR41

**Comment by mTwTm** [comment]
Should be improved in #391, specifically 83358b9
