### ISSUE TITLE
[dogfooding] to gray out back and forward buttons according to current status

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#173]
Should Disable back and forward button when at the first or last webpage of browsing stack

**Comment by Conjuror** [comment]
Suggest to fix it before code freeze. @chianger

**Comment by Conjuror** [comment]
Currently, it's been gray out while loading. I am not sure if we should change the icon to X. @carol_mozilla ?

**Comment by mTwTm** [comment]
It's tracked on #328
