### ISSUE TITLE
Change activity name to correct one

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#178]
Currently package name and activity name are still focus.
We should change them accordingly.

package:/data/app/gro.allizom.zelda.beta-1/base.apk=gro.allizom.zelda.beta

**Comment by mTwTm** [comment]
@idiotmax I suppose you have fixed this already?

**Comment by idiotmax** [comment]
Closed by #708 #710 #712

**Comment by Conjuror** [comment]
Verified in build 972
