### ISSUE TITLE
[Home screen] Major floating functional buttons (search, menu, home UI only)

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/Zerda#18]
acceptance criteria:
1. able to see the three floating buttons on top of the web page area.
2. Buttons automatically hide as user scrolls up and down.
3. Search button triggers the search panel; menu button triggers the menu panel; home button triggers to home page.

**Comment by idiotmax** [comment]
Fix 2 in follow up issue #35
Fix 3 in individual depending bug #19, #20, #36

**Comment by Conjuror** [comment]
Tested in build 86. resolved fixed.
