### ISSUE TITLE
menu icons overlap with description

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#180]
As title. This happens on small devices. i.e. Lenovo VibeA.
Build 234
Reproduce rate: 100%

**Comment by Conjuror** [comment]
https://drive.google.com/a/mozilla.com/file/d/0B11T5xYLeXAOcVBRaFRSaV9KcW8/view?usp=sharing

**Comment by mTwTm** [comment]
Will need to check if it fixes with the new font size in UI spec V2. This may get worse for other languages.

**Comment by mTwTm** [comment]
@walkingice can you keep an eye on this issue when you're updating the menu? 😃

**Comment by chianger** [comment]
making this P1, and let's revisit once string freeze

**Comment by Conjuror** [comment]
dup.

**Comment by dakaizou** [comment]
Verified in build 540
