### ISSUE TITLE
For some image the "Download Image" context menu is not shown 

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/Zerda#187]
Search "vimeo" for image result. Some of the result can be downloaded and some cannot. (Works on Chrome.)

**Comment by mTwTm** [comment]
This one: https://www.google.com.tw/search?q=vimeo&prmd=vin&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiY3oOw1MvVAhVFNrwKHarICO8Q_AUIESgC&biw=360&bih=527

**Comment by Conjuror** [comment]
All web compat are tracked with #342. Since it's not Top 100 ID sites, keep it alive and track separately.

**Comment by Conjuror** [comment]
[WebCompat] Engineering to take a look in Sprint 6

**Comment by Conjuror** [comment]
still have it in build 623

**Comment by Conjuror** [comment]
#454

**Comment by dakaizou** [comment]
It seems like base64 will dismiss the Save image option
![screenshot](https://lh3.googleusercontent.com/-eG0SOLUcUSE/WbDlPpOHSAI/AAAAAAAAAdE/e46S9CHgGXo3YolLH0eupIxJJsdHsgHtgCL0BGAYYCw/h1920/3361212622352321771%253Faccount_id%253D3)

**Comment by dakaizou** [comment]
Possibly related to #341

**Comment by mTwTm** [comment]
Invalid since we have changed the user agent and in turn the responding google page.

**Comment by Conjuror** [comment]
We'll test it again and see if it can be reproduced now.

**Comment by dakaizou** [comment]
verified as invalid
