### ISSUE TITLE
Some svg icons are corrupted on specific devices.

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/Zerda#188]
@Conjuror Do you know which device?

**Comment by mTwTm** [comment]
It's 5.X Z3c

**Comment by Conjuror** [comment]
Also for small devices, i.e. Andromax and Lenovo

**Comment by Conjuror** [comment]
It seems all the devices here are corrupted

**Comment by Conjuror** [comment]
Plan to revisit it w/ tomorrow nightly build

**Comment by Conjuror** [comment]
it seems all good now. build 492
