### ISSUE TITLE
Onboarding pages

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/Zerda#189]
Leveraging the existing onboarding slides, and polish with Zerda contents.
+ switching speed mode is required.
Required material:
1. Zerda style graphics
2. Mkt messages  (due Sep1)

**Comment by chianger** [comment]
@joechengla

**Comment by harly21** [comment]
Carol has released the visual spec for onboarding: https://drive.google.com/open?id=0B-9PIePlQZRlWGRnRE1QVFkzMGs

**Comment by walkingice** [comment]
![firstrun](https://user-images.githubusercontent.com/54793/30059746-fd91e470-9272-11e7-8d23-cab506397ea6.png)

Current spec haven't specify height of card, therefore in second page we got this. Maybe we should adjust height of the card? (Currently it is **460dp**)

**Comment by Conjuror** [comment]
Verified in build 887
