### ISSUE TITLE
[Smoke Test] Vimeo video paused automatically 

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#196]
Vimeo video automatically paused without touch. The time it stopped is between 00:10~01:00

Reproduce rate: 90%

DuT: Advan i5C

Build 264

**Comment by Conjuror** [comment]
note that user cannot resume to play. it's stuck.

**Comment by Conjuror** [comment]
checked on Andromax and Lenovo VibeA, won't happen. Move to P1 as WebCompat issue

**Comment by dakaizou** [comment]
Verified in build 623
DuT: Advan

**Comment by dakaizou** [comment]
Removed QAwanted since verified
