### ISSUE TITLE
Long page screenshot enhancements: UI

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/Zerda#199]
1. Show a "Open" action in Complete snack bar
2. Update downloading animation

**Comment by mTwTm** [comment]
These are currently UX/UI unready. They are originally not planned in Sprint 4 though. @chianger I'll temporarily put these into sprint 5 and let's rearrange in sprint planning.

**Comment by mTwTm** [comment]
Fixed in #514

**Comment by Conjuror** [comment]
Looks good to me on Build 790. Closed as verified.
