### ISSUE TITLE
[home screen] Menu panel (UI only)

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/Zerda#20]
acceptance criteria:
able to bring up the menu panel with a list of icons (non-functioning)

Depends on: #62, #67, #68, #69, #70

**Comment by chianger** [comment]
remaining open issues #67 #68 #70 are tracked under Feature_FollowUp, and moved to sprint4.
I think we can consider current one as CLOSED and let QA verify.

**Comment by Conjuror** [comment]
worked in build 121
