### ISSUE TITLE
Change long-screenshot folder name

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/Zerda#224]
Originally in #200, we should also remember Zerda is the project name so we are not necessarily calling the Folder we're saving "Zerda"

We should also discuss if we want to differentiate between release and debug build.

**Comment by idiotmax** [comment]
Product name confirmed? "Firefox Rocket"?

**Comment by Conjuror** [comment]
Build 972. Confirmed on FirefoxRocketNightly
