### ISSUE TITLE
Please update configuration or disable telemetry

### ISSUE THREAD

**Issue by pocmo** [mozilla-tw/Zerda#236]
Please disable our remove the telemetry code:
https://github.com/mozilla-tw/Zerda/blob/7c1633954669a45e37970c9fb54e464e3c8f767a/app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.java

Currently your non debug builds are configured to upload telemetry as Focus/Klar.

**Comment by mTwTm** [comment]
Closed with #250

**Comment by Conjuror** [comment]
no QA work here :D
