### ISSUE TITLE
Screenshot will crash if Zerda app has not been granted media permission already

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Zerda#239]
![screenshot_20170814-170144](https://user-images.githubusercontent.com/7221296/29265158-7df8ffee-8112-11e7-8dd1-d920e7720869.png)

**Comment by mTwTm** [comment]
@joechengla Can't reproduce with the STR, there is crash stack from Buddybuild but the symptom is more like: Crashing when trying to capture but the activity is already paused.

Is this 100% reproduced? If not, did you switch to other Apps or press home button when the crash happens?

**Comment by mTwTm** [comment]
This the manual report for is #230
