### ISSUE TITLE
First download after asking storage permission is ignored.

### ISSUE THREAD

**Issue by dakaizou** [mozilla-tw/Zerda#243]
STR:
1. Revoke the storage permission
2. Download a file
3. Grant permission

Build: 303

**Comment by mTwTm** [comment]
Same for screen shot

**Comment by walkingice** [comment]
In this commit I added one line to fix a issue of permission check, not sure whether it effect this bug, but worth to give a try.
https://github.com/mozilla-tw/Zerda/commit/624a65b18ec238582e607e81257a8a94ff65ed24

**Comment by mTwTm** [comment]
@walkingice Yeah I saw your commit and tried but no luck so far. I'll deep dive when I have time, thanks!!

**Comment by mTwTm** [comment]
Fixed in 624a65b18ec238582e607e81257a8a94ff65ed24

**Comment by Conjuror** [comment]
Looks good on build 540. Closed as verified.
