### ISSUE TITLE
Bottom bar blocks wikipedia citation 

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Zerda#255]
![screenshot_20170815-100844](https://user-images.githubusercontent.com/7221296/29299520-e389034c-81a1-11e7-8a60-cd4b1fe752a1.png)

goto wikipedia, and click on citations such as [1], and you will see the citation black bar being blocked by bottom bar

**Comment by Conjuror** [comment]
other example: google map floating button is covered by zerda bottom action bar

**Comment by mTwTm** [comment]
Duplicate to #166

**Comment by dakaizou** [comment]
Invalid
