### ISSUE TITLE
snackbar while screen capture is done should be with "SHARE"

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#257]
as title
build 357

**Comment by chianger** [comment]
Need visual to design the button on snackbar

**Comment by carol-mozilla** [comment]
please add "SHARE" on the right side of the snackbar as the system style.

**Comment by harly21** [comment]
@chianger Do we need visual or snackbar is a standard Android component?

**Comment by mTwTm** [comment]
@harly21 It's a standard one but we can customize it if we want to. Focus did this, see https://github.com/mozilla-mobile/focus-android/issues/193 . With little effort we can change the text (color, gravity, alignment), the backgroundcolor, foregroundcolor...etc

**Comment by chianger** [comment]
thanks for the info. since VD has accepted the standard style, let's just go with it.

**Comment by dakaizou** [comment]
verified in build 790
