### ISSUE TITLE
[dogfooding] Hit area of Context menu for history is too small

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#267]
Build 357
all devices will have the same issue. Once the issue is fixed, it should cover the refine from Visual Designer for title/URL layout, buttom, icons, and width of context menu entry button.

**Comment by Conjuror** [comment]
note that for web page without favicons, we should have a default favicon for it.

**Comment by mTwTm** [comment]
The history is also overlapping the context menu button on small devices.

**Comment by mTwTm** [comment]
I'll file another item for the favicon part.

**Comment by Conjuror** [comment]
favicon part: #288

**Comment by carol-mozilla** [comment]
Please set the “hit area" to 56dp x 56dp(mdpi) thanks!

**Comment by idiotmax** [comment]
Fixed in #426

**Comment by Conjuror** [comment]
good for build 636
