### ISSUE TITLE
menu bar buttons needs to be rearranged

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#268]
For small devices, menu bar button and the navigation bar need to rearrange buttons' location.
Build 357

**Comment by Conjuror** [comment]
label VD for VD's input

**Comment by mTwTm** [comment]
This is already according to the spec (57dp space between items)

**Comment by harly21** [comment]
Could you give a screenshot on the small device?

**Comment by Conjuror** [comment]
As your with 👍 
DuT: Andromax
Build 471

![small_device_menu](https://user-images.githubusercontent.com/1625148/29603267-1b3840ee-8816-11e7-9533-b48e33d07e25.png)

**Comment by mTwTm** [comment]
Spec change to be updated: the interval is 50dp instead of 57dp when on devices smaller than 320dp

**Comment by Conjuror** [comment]
looks good on build 636
