### ISSUE TITLE
[dogfooding] download toast behaviour refinement

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#270]
as title

build 357

**Comment by mTwTm** [comment]
Only for clicking download lists, not including from context menu.

**Comment by chianger** [comment]
exclude image file.

**Comment by Conjuror** [comment]
To clarify, if download starts with context menu → no banner for being started
if download starts without context menu → banner for being started
After downloading → banner for completeness

**Comment by mTwTm** [comment]
Fixed in #811, #910

**Comment by dakaizou** [comment]
verified in build 1512
