### ISSUE TITLE
[dogfooding] Need pressed state for History items

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#276]
Build 357.

Labelled VD for VD's input

**Comment by harly21** [comment]
not just history, but also download and screenshot panel. Also tap on menu should have hightlight as well

**Comment by Conjuror** [comment]
As your wish 👍 

DuT: Andromax
Build 471

![small_device_menu](https://user-images.githubusercontent.com/1625148/29603232-ecddab80-8815-11e7-8b00-c4ecab9a197f.png)

**Comment by mTwTm** [comment]
Fixed in #413

**Comment by cssjh** [comment]
**Verified** in build 636
