### ISSUE TITLE
[dogfooding] After loading small web site, no fading out animation of loading

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#277]
build 357

**Comment by Conjuror** [comment]
progress bar.

**Comment by Conjuror** [comment]
1. Launch Zerda
2. Visit https://www.paypal.com and observe the progress bar

Expected Result:

2. the animation of progress bar should be completed (both fade in and fade out)

Actual Result:

2. The animation didn't fade out but disappear.

**Comment by dakaizou** [comment]
Verified in build 623

**Comment by dakaizou** [comment]
Reopen this since it's happening in [https://www.amazon.com](https://www.amazon.com), related to #334

**Comment by Conjuror** [comment]
Close this one and track with #334. We don't need to have 2 issues for the same behavior :)
