### ISSUE TITLE
[dogfooding] Download / History panel cannot cover full screen

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#284]
build 357

as title. Happened on small devices. Lenovo VibeA

**Comment by mTwTm** [comment]
I tend to believe it's device related rather than screen size related. Did not happen on my 3.2" emulator

**Comment by Conjuror** [comment]
Z3C also have the same situation

**Comment by idiotmax** [comment]
Check if window style is NoActionBar, false could be the root cause. Reproducible on L, remember to verify on multiple framework version.

**Comment by dakaizou** [comment]
verified in build 1019
