### ISSUE TITLE
[dogfooding] Color theme for Zerda

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#285]
as title. leave to VD & UX for inputs

**Comment by harly21** [comment]
Can you be more specific on what this is about?

**Comment by Conjuror** [comment]
This is an issue holder for Zerda theme. Per previous discussion, we'll have a whole new color theme for Zerda. Once VD complete the design, we'll have it close and create issues to track engineering work.

**Comment by harly21** [comment]
Got it, thanks for the quick reply

**Comment by harly21** [comment]
Spec for the new color theme has been delivered: https://drive.google.com/file/d/0B-9PIePlQZRlNUVWUkk4YmxwQ2c/view?usp=sharing

**Comment by cssjh** [comment]
Dup
Meta #628
