### ISSUE TITLE
Screenshot won't work on Andromax device

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#286]
Unable to take screenshot.

Build 357

**Comment by Conjuror** [comment]
https://drive.google.com/a/mozilla.com/file/d/0B11T5xYLeXAOMmg4YUNuSl9YVWs/view?usp=sharing

**Comment by mTwTm** [comment]
This would be tough... It would be a red flag if many DuT suffers from this.

**Comment by Conjuror** [comment]
Investigate root cause. If there's no actionable for us, put it to P2 and block Andromax to download from Google play.

**Comment by Conjuror** [comment]
Cannot reproduce now. Close it as invalid.

**Comment by Conjuror** [comment]
Build 623
