### ISSUE TITLE
No default favicon for sites without favicon in history list

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/Zerda#288]

**Comment by chianger** [comment]
Need VD

**Comment by carol-mozilla** [comment]
Cloud we reference on Fennec's "bookmark Favicon"? @mTwTm

**Comment by mTwTm** [comment]
@carol-mozilla current implementation is a Globe, I'm not sure if that is from you but I'll first close this. Let's file a bug if we want to change it to bookmark

**Comment by mTwTm** [comment]
Fixed in #412

**Comment by cssjh** [comment]
**Verified** in build 636
