### ISSUE TITLE
[Smoke Test] Unable to get geolocation for google map (and other websites) for the first time

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#295]
as title.

Build 382

STR:
1. Launch Zerda and visit maps.google.com
2. tap "current position" button on the bottom-right

Expected Result:
2. Be able to see map about current position

Actual Result:
2. No response

**Comment by mTwTm** [comment]
Related to #243

**Comment by mTwTm** [comment]
Fixed in 624a65b18ec238582e607e81257a8a94ff65ed24

**Comment by Conjuror** [comment]
build 492.
