### ISSUE TITLE
[Smoke Test] Panel behaviours is incorrect

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#296]
According to spec: Page No. 8, [Zerda] Menu,Panel,Download,History_v.1.6.pdf

it's all about the release position of drag action to decide the change of panel size. Currently, we only detect the trace of drag.

Build 358

**Comment by mTwTm** [comment]
This would be a big one to deal with, not going to look into this before we concluded this is P1

**Comment by mTwTm** [comment]
Current behavior is acceptable, UX to change the spec.

**Comment by Conjuror** [comment]
Closed as invalid
