### ISSUE TITLE
The UrlFragment can be added for multiple times

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/Zerda#33]
STR:
1. Click search FAB
2. Press back to hide the keyboard
3. repeat step 1-2

Expected result:
UrlFragment is added only once.

Actual result:
UrlFragment is added for multiple times, to get back to Top site several back press is needed.

**Comment by Conjuror** [comment]
not a valid issue anymore due to spec change. Close it for now. Please reopen it if I misunderstand it.
