### ISSUE TITLE
[Smoke Test] URL bar is hidden if a user hides URL bar in previous page

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#335]
Build 439

STR:
1. Launch Zerda and visit a webpage longer than screen resolution
2. Scroll down
3. Tap home
4. Launch another webpage which is longer than screen resolution

Expected Result:

4. Able to see URL bar and progress bar animation

Actual Result:

4. URL bar is hidden and no progress bar

**Comment by chianger** [comment]
Will be fixed once #322  done

**Comment by Conjuror** [comment]
Wait for #322
