### ISSUE TITLE
Download/History Panel UI: list & item layout with BottomSheet in a Fragment

### ISSUE THREAD

**Issue by idiotmax** [mozilla-tw/Zerda#34]
function piece is covered in #43

Depends on: #12, #43, #75

**Comment by chianger** [comment]
we traded this with #14 so this one goes to sprint#3

**Comment by mTwTm** [comment]
@WeiWW I have unblocked #75, see the commit message ( https://github.com/mozilla-tw/Zerda/pull/76/commits/84bbaf6a181159eff8c49589b0b1dba4024da0eb ) for details and let me know if this implementation leads to performance issues.

**Comment by chianger** [comment]
carryover to sprint4

**Comment by WeiWW** [comment]
@mTwTm  Okay, I will notice whether BottomSheetDialog leads to any performance issues.

**Comment by mTwTm** [comment]
I'm going to take a look on how to add those tabs. If anyone is already doing this please let me know :D. @WeiWW are you already on this?

**Comment by WeiWW** [comment]
@mTwTm No,you can take this.

**Comment by Conjuror** [comment]
good in build 357
