### ISSUE TITLE
[Meta] [WebCompat] Top 100 websites in Indonesia

### ISSUE THREAD

**Issue by dakaizou** [mozilla-tw/Zerda#342]
Updated at 09/26 10:47
- [ ] cnnindonesia.com - mixed content and ad banner
- [ ] detik.com - mixed content
----------------------------
[all screenshots](https://drive.google.com/open?id=0B0uVZlaHN366SW5vc3BBbVlSd00)
[Alodokter.com](http://www.alodokter.com) - ~~no picture~~
[Blogspot.com](http://dianarikasari.blogspot.com/) [2](http://amriawan.blogspot.com) [3](http://separonyolong.blogspot.tw) - ~~can't read entire paragraphs~~, screenshot can only capture part of the page
[Bukalapak.com](https://www.bukalapak.com/) - some pictures are gone, icons become numbers
[Detik.com](https://www.detik.com) - ~~no picture~~
[Duniaku.net](https://www.duniaku.net/) - no picture, icons become Chinese characters
[Grid.id](http://www.grid.id/) - ~~no css styling~~
[Shopee.co.id](https://shopee.co.id/) - ~~total blank~~
[Detik.com](https://www.detik.com/) - ~~some pictures are gone~~
[Idntimes.com](https://www.idntimes.com/) - ~~some pictures are gone~~, icons become weird characters
[Okezone.com](https://www.okezone.com/) - icons become weird characters
[Savefrom.net](http://savefrom.net) - ~~some contents are gone~~
[Traveloka.com](https://www.traveloka.com) - ~~most of the contents are gone~~
[Tribunnews.com](http://tribunnews.com) - icons become weird characters
[Txxx.com](http://Txxx.com) - icons become weird characters
[Viva.co.id](http://viva.co.id) - ~~some pictures are gone~~, icons become weird characters

~~Strike out~~ means that it happens in Focus as well, when switching on **_Block other content trackers_** option in Focus

Build: 439
DuT: Advan

**Comment by dakaizou** [comment]
[all screenshots](https://drive.google.com/open?id=0B0uVZlaHN366UXRESnBPelZzS0k)
[Alodokter.com](http://www.alodokter.com) - no picture
[Bukalapak.com](https://www.bukalapak.com/) - some pictures are gone
[Duniaku.net](https://www.duniaku.net/) - no picture, icons become Chinese characters
[Grid.id](http://www.grid.id/) - ~~no css styling~~
[Idntimes.com](https://www.idntimes.com/) - ~~some pictures are gone~~, icons become weird characters
[Kumparan.com](Kumparan.com) - icons become Chinese characters
[Okezone.com](https://www.okezone.com/) - icons become weird characters
[Savefrom.net](savefrom.net) - ~~some contents are gone~~
[Shopee.co.id](https://shopee.co.id/) - ~~total blank~~
[Simpkb.id](Simpkb.id) - icons become Chinese characters
[Sindonews.com](Sindonews.com) - icons become weird characters
[Solidfiles.com](Solidfiles.com) - icons become weird characters
[Suara.com](Suara.com) - icons become Chinese characters
[Tabloidbintang.com](Tabloidbintang.com) - icons become weird characters
[Traveloka.com](traveloka.com) - ~~most of the contents are gone~~
[Tribunnews.com](tribunnews.com) - icons become weird characters
[Viva.co.id](viva.co.id) - ~~some pictures are gone~~, icons become weird characters

~~Strike out~~ means that it happens in Focus as well, when switching on **_Block other content trackers_** option in Focus

Build: 461
DuT: Samsung J7 Prime

**Comment by dakaizou** [comment]
[all screenshots](https://drive.google.com/open?id=0B0uVZlaHN366UjVJM0VtT2YzV0U)

### Picture
[Alodokter.com](http://www.alodokter.com) - no picture
[Detik.com](www.detik.com) - ~~no picture~~
[Duniaku.net](https://www.duniaku.net/) - no picture
[Idntimes.com](https://www.idntimes.com/) - ~~some pictures are gone~~
[Viva.co.id](viva.co.id) - ~~some pictures are gone~~

### Font
[Duniaku.net](https://www.duniaku.net/) - icons become Chinese characters
[Idntimes.com](https://www.idntimes.com/) - icons become weird characters
[Kumparan.com](Kumparan.com) - icons become Chinese characters
[Okezone.com](https://www.okezone.com/) - icons become weird characters
[Simpkb.id](Simpkb.id) - icons become Chinese characters
[Sindonews.com](Sindonews.com) - icons become weird characters
[Solidfiles.com](Solidfiles.com) - icons become weird characters
[Suara.com](Suara.com) - icons become Chinese characters
[Tabloidbintang.com](Tabloidbintang.com) - icons become weird characters
[Tribunnews.com](tribunnews.com) - icons become weird characters
[Txxx.com](Txxx.com) - icons become weird characters
[Viva.co.id](viva.co.id) - icons become weird characters

### Other
[Bukalapak.com](https://www.bukalapak.com/) - loading time over five minutes
[Grid.id](http://www.grid.id/) - ~~no css styling~~
[Shopee.co.id](https://shopee.co.id/) - ~~total blank~~
[Traveloka.com](traveloka.com) - ~~most of the contents are gone~~


### Note
~~Strike out~~ means that it happens in Focus as well, when switching on **_Block other content trackers_** option in Focus

Build: 492
DuT: mito

**Comment by Conjuror** [comment]
By @mTwTm  on #89 about failed on loading [bukalapak.com](bukalapak.com) on Samsung J7 prime
> P.S. A plain Webview failed to show the banner marquee, too. We would need to investigate further what's happening.
> Personally I would suggest this to happen in Sprint 4 to have a better understanding to what problems we may face in terms of compatibility as early as possible.

**Comment by Conjuror** [comment]
update [comment](https://github.com/mozilla-tw/Zerda/issues/342#issuecomment-324553376) for tracking failing to load tokopedia.com on mito, close #261 for better tracking.

**Comment by chianger** [comment]
we'll need a another round of webcompat testing on a special configuration (tracking blocker All off). It requires a special build

**Comment by dakaizou** [comment]
all screenshots [samsung](https://drive.google.com/open?id=0B0uVZlaHN366Vml5ZlRiSEVldjg) [advan](https://drive.google.com/open?id=0B0uVZlaHN366YjFzd0tIVVZrckE) [mito](https://drive.google.com/open?id=0B-hmv-8fniTNVUMzd3JSTHBZVzA)

### Picture
[Detik.com](http://www.detik.com/) - ~~no picture~~


### Note
~~Strike out~~ means that it happens in Focus as well, when switching on **_Block other content trackers_** option in Focus

Build: 592
DuT: Samsung J7 Prime, advan

**Comment by cssjh** [comment]
### Picture
[cnnindonesia.com](cnnindonesia.com) - ~~some pictures are not loaded~~
*Screenshots: [Samsung](https://drive.google.com/drive/folders/0B0uVZlaHN366QkFJVllyREZxTkk), [Mito](https://drive.google.com/drive/folders/0B-hmv-8fniTNVEdhNHhTMDlTamM)*

### Crash
[tabloidbintang.com](tabloidbintang.com) - crashes only on Mito
*Screenshots: [Mito](https://drive.google.com/drive/folders/0B-hmv-8fniTNcEtTVDVkOEtrdTA)*

### Note
~~Strike out~~ means that it happens in Focus as well.

**Build:** 592 (Block image off)
**DuT:** Mito, Samsung J7 Prime

**Comment by Conjuror** [comment]
[WebCompat] Engineering to study tokopedia issues

**Comment by Conjuror** [comment]
#454 to track

**Comment by Conjuror** [comment]
Detik.com close turbo mode still can't display some images

**Comment by cssjh** [comment]
*(~~Strike out~~ means that it happens in Focus as well.)*

### Image
cnnindonesia.com - ~~most images are missing~~

### Other
www.blibli.com - will be redirected to www.blibli.com/unsupported-browser

**Comment by chianger** [comment]
this is a webcompat meta, but I assume Ann can firstly take look into most of the issues.

**Comment by WeiWW** [comment]
I separately  build MixedContent enable and disable in #749. Maybe can help QA test this issues.

**Comment by Conjuror** [comment]
QA is in progress. Thanks to @dakaizou

**Comment by dakaizou** [comment]
Most images are working fine with mixed content enabled. Just a few ad banners (cnnindonesia) are still missing.
Screenshots on [Advan](https://drive.google.com/drive/folders/0B0uVZlaHN366c2hsVXpSVGkxRms) and [Samsung](https://drive.google.com/drive/folders/0B0uVZlaHN366TEVmWUhkWnhOSE0)

Build: 980
DuT: Advan, Samsung

**Comment by idiotmax** [comment]
@dakaizou Is the ad banner still missing when turbo mode is off?
@joechengla We need you review the testing result of [Indo Top 100] to make the product decision. Are we going to allow mix content setting as "MIXED_CONTENT_COMPATIBILITY_MODE"?

**Comment by dakaizou** [comment]
@idiotmax Yes, it is. 
zerda screenshot
![zerda](https://lh3.googleusercontent.com/-Zt6ZgS3VWpE/WboL2Qb5-6I/AAAAAAAAAlw/scgG7mwxmJMh2583SnkIp3oCShmW20mPwCL0BGAYYCw/h1920/6474136969942497715%253Faccount_id%253D3)
chrome screenshot
![chrome](https://lh3.googleusercontent.com/-6ZPW6jV6aoA/WboL17tWVxI/AAAAAAAAAlg/JVpsemesW-0xVfMo8sFLkYA8oo8m63B_ACL0BGAYYCw/h1920/5569244513667035738%253Faccount_id%253D3)

**Comment by dakaizou** [comment]
Pictures of [Cnnindonesia.com](https://www.cnnindonesia.com) will vanish when finishing loading.
See [recording](https://drive.google.com/file/d/0B0uVZlaHN366NlpXWWRrdmI2N0E/view?usp=sharing)

Build: 1072
DuT: Advan, Samsung

**Comment by chianger** [comment]
QAWAnted to verify blibli.com.

**Comment by dakaizou** [comment]
@chianger blibli.com now works fine on build 1238

DuT: Oppo, Samsung

**Comment by chianger** [comment]
Closing this one since the left two issues are all mixed content websites. Will track that under #954
