### ISSUE TITLE
History panel is freezing in the initial 10 seconds

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/Zerda#344]
Some heavy loading is happening on the UI thread. This may happen only with a really big history list.

**Comment by dakaizou** [comment]
Still happening in build 623
DuT: Sony Z3C

**Comment by chianger** [comment]
QAWanted to check if it happens when history is a big list.

**Comment by dakaizou** [comment]
We'll check MTBF devices tomorrow (build 1124)

**Comment by dakaizou** [comment]
Still happening in build 1158
See [recording](https://drive.google.com/file/d/0B0uVZlaHN366ZzRFalFDMjl5LXM/view?usp=sharing)

**Comment by mTwTm** [comment]
@dakaizou does this happen on non-sony devices? We would like to decide if we're going to deal with this depending on whether this only happens on Sony. Add QAwanted again for this reason.

**Comment by dakaizou** [comment]
@mTwTm Yes, it does.
See recording: [samsung](https://drive.google.com/open?id=0B0uVZlaHN366d3FqRTNHT3dGOFU), [oppo](https://drive.google.com/open?id=0B0uVZlaHN366cV9nYkxUNTdleTQ), [mito](https://drive.google.com/open?id=0B0uVZlaHN366Wi1McEJxVDBOVWc)

Note: Tested with the following line added to HistoryProvider.insertWithUrlUnique()

> for (int i = 0; i < 100; i++) id = db.insert(Tables.BROWSING_HISTORY, null, values);

**Comment by mTwTm** [comment]
Possible root cause: onScrolled is fired continuously until every item is loaded.

**Comment by dakaizou** [comment]
verified in build 1372
