### ISSUE TITLE
[dogfooding] Icon sizes are different on the menu

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#348]
Build 461.

It seems the icons on menu are in different sizes. Please have it check.

**Comment by idiotmax** [comment]
According to the screenshot, menu_delete seems to have a little border comparing to others. Need VD confirm source image.

![menu_delete_seems_smaller](https://user-images.githubusercontent.com/441664/29618051-6f579ade-8849-11e7-92ed-9b536b0299f2.png)

**Comment by mTwTm** [comment]
I'm on this already, the icon size is also not aligning the VD spec

**Comment by mTwTm** [comment]
Oh, I saw you are also on this, I'll first change the icon size to align spec tomorrow. (It has some undocumented border because of being ImageButton rather than Imageview)

**Comment by mTwTm** [comment]
Spec update: icons are all 24dp

**Comment by mTwTm** [comment]
The icons are bigger on their own. It's a VD's call

**Comment by dakaizou** [comment]
See meta issue #628

**Comment by dakaizou** [comment]
verified in meta issue
