### ISSUE TITLE
[dogfooding] Some YouTube live event playback is not supported

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#351]
as title.
Build 461

**Comment by Conjuror** [comment]
All web compat are tracked with #342. Keep it separately to track

**Comment by WeiWW** [comment]
Use chrome dev tool to inspect web page source, just suddenly see alert but don't know what trigger this alert. Dev tool neither show any error or warnings.

**Comment by Conjuror** [comment]
build 702. verified.
