### ISSUE TITLE
[dogfooding] search and menu function on top left corner of tribunnews.com are not accessible

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#355]
as title

build 461

**Comment by Conjuror** [comment]
we'll need to figure out the root cause.

**Comment by Conjuror** [comment]
Put STRwanted to have QA investigate more information on it.

**Comment by Conjuror** [comment]
Could be effeced by other tracker, QA to track

**Comment by dakaizou** [comment]
Verified in build 702
