### ISSUE TITLE
[dogfooding] YouTube favicon not working (it's low resolution)

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#359]
as title

build 461

**Comment by Conjuror** [comment]
related to #361

**Comment by chianger** [comment]
stays at P0 for now but we should revisit during sprint6 planning

**Comment by mTwTm** [comment]
move to decision pending based on @chianger 's comment

**Comment by joechengla** [comment]
isn't this fixed now? blurry icons will show "Y"?

**Comment by Conjuror** [comment]
I think so. There's other issues about cannot extract background color of Y if a user doesn't wait until loading is done.

**Comment by chianger** [comment]
no longer having low resolution icon now.

**Comment by Conjuror** [comment]
build 1072
