### ISSUE TITLE
[dogfooding] favicon with background design

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#361]
build 461

as title

**Comment by Conjuror** [comment]
for home screen

**Comment by chianger** [comment]
depends how much we can do in sprint6 and also need an effort assessment on this. 
it's likely either P0 (do it now) or P2 (next release).

**Comment by Conjuror** [comment]
To be more specific, we'd like to have Zerda Top Sites have the same effects as ActivityStream.

**Comment by dakaizou** [comment]
verified in build 790
