### ISSUE TITLE
Update send usage data string in setting

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Zerda#375]
Refer to https://bugzilla.mozilla.org/show_bug.cgi?id=1390689
Max and Jack has access to this bug

**Comment by Conjuror** [comment]
@chianger no sure which category you prefer. remove bug to avoid pollute the pool

**Comment by chianger** [comment]
yes. let's track in Zerda V1.0.

**Comment by Conjuror** [comment]
How should I verify access to Telemetry?

**Comment by Conjuror** [comment]
This will be hard for QA to verify. Leave it open as low priority
