### ISSUE TITLE
[Smoke Test] bottom banner is covered by menu bar

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#381]
build 471
as title

**Comment by Conjuror** [comment]
![Uploading chrome_bottom.png…](Chrome)
![Uploading zerda_bottom.png…](Zerda)

**Comment by Conjuror** [comment]
![chrome_bottom](https://user-images.githubusercontent.com/1625148/29595363-8a97a8c6-87e9-11e7-9140-d69fbc0434eb.png)
![zerda_bottom](https://user-images.githubusercontent.com/1625148/29595364-8abee864-87e9-11e7-83f5-ad42adb54656.png)

**Comment by mTwTm** [comment]
Can't reproduce. Also I'd like to make sure, is the bug about: "The bottom of the page is still gone even without url bar"?

**Comment by Conjuror** [comment]
it should have a gray banner with FB and LINE links on it. It seems the banner is be covered by menu bar.

DuT: Andromax, Samsung J7 Prime
Build: 471
Reproduce rate: 100%

Tested w/ the page: http://wealth.businessweekly.com.tw/GArticle.aspx?id=ARTL000095802

**Comment by mTwTm** [comment]
Hmm this is not reproducing on my Sony XA and Pixel, this is why I asked for clarification. Well noted thanks!

**Comment by Conjuror** [comment]
Cool. I didn't expect that because I can also see that on my Pixel. 👍

**Comment by mTwTm** [comment]
Oops, it's not showing on my Sony but it's on Pixel, should have double checked, sorry.

**Comment by mTwTm** [comment]
It's still there after #399, the website might be doing some other tweak. I'll check what happens on other browser with bottom bar.

**Comment by chianger** [comment]
Worksforme now.

**Comment by dakaizou** [comment]
verified in build 943
