### ISSUE TITLE
The title of the same top site tiles are changing

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/Zerda#386]
STR:

Click on top site A, click home, click on top site b, click home, for the same tile, sometimes url is shown while sometimes page title is shown.

See the Mozilla tile in following screenshots:

![screenshot_20170823-130712](https://user-images.githubusercontent.com/6755074/29599735-5105ec4c-8804-11e7-8650-4c8667d5efae.png)
![screenshot_20170823-130725](https://user-images.githubusercontent.com/6755074/29599736-510ccf80-8804-11e7-8c02-68dfae02c7bf.png)

**Comment by mTwTm** [comment]
STR: 
1. Clicking a page with a title again and again to make it a top site (It will be labeled with its title, such as Yotubue if you're trying with yotube.com)
2. Click another top site, the youtube topsite label becomes http://m.youtu....

**Comment by dakaizou** [comment]
verified in build 790
