### ISSUE TITLE
Update Top Sites

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Zerda#398]
In this order below. Thanks

https://www.youtube.com/
http://www.detik.com/
http://www.tribunnews.com/
https://www.facebook.com/
https://www.tokopedia.com/
http://www.liputan6.com/
http://www.kompas.com/
https://www.bukalapak.com/

**Comment by chianger** [comment]
P1 feature

**Comment by idiotmax** [comment]
BrowsingHistory.topsiteQuery(8 entry, count 3)

14,12,10,8
6,5,4,3

**Comment by idiotmax** [comment]
BrowsingHistory.topsiteQuery(8 entry, count 3)

14,12,10,8
6,5,4,3

Youtube,14
...
bukalapak,3

**Comment by Conjuror** [comment]
Verified for now as we are at build 790. Some Top Sites issues are tracked.
