### ISSUE TITLE
History placeholder is too close to clear browsing history button

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#408]
build 525.

**Comment by Conjuror** [comment]
Spec
<img width="191" alt="screenshot 2017-08-25 at 09 26 13" src="https://user-images.githubusercontent.com/1625148/29695868-d1791b78-8977-11e7-98ac-9510117b8728.png">

**Comment by Conjuror** [comment]
![history](https://user-images.githubusercontent.com/1625148/29695880-e16a18b6-8977-11e7-924a-fc64d25d1a5b.png)

**Comment by mTwTm** [comment]
Clear browsing history button itself should also be hidden when placeholder is shown.

**Comment by Conjuror** [comment]
invalid due to #367
