### ISSUE TITLE
[Smoke Test] Forward, refresh, share, capture not refreshed when the menu is opened

### ISSUE THREAD

**Issue by dakaizou** [mozilla-tw/Zerda#410]
STR:
1. Go to any page (e.g. [tokopedia.com](https://m.tokopedia.com))
2. Before the page is ready, tap the menu button
3. Wait til the page is ready, those buttons are still disabled

Build: 525
DuT: Samsung J7 Prime

**Comment by mTwTm** [comment]
To be more specific: the current implementation does not refresh when the menu is opened. It is refreshed every time the menu is opened. Suggesting this to be a P1 bug...

**Comment by mTwTm** [comment]
Note: behavior should also tune to actions are available whenever onPageLoadStarted rather than onPageFinished

**Comment by dakaizou** [comment]
verified in build 855
