### ISSUE TITLE
Fine tune refresh when speed mode or block image is toggled.

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/Zerda#418]
UX spec has specified to not reload when block image setting is enabled.
For disable, webview will load pending items (auto-reload) after change so I'm proposing the same.
Current implementation always refresh after setting is changed, this should be changed.

We're doing the similar to speed mode: only refresh when speed mode is disabled.

**Comment by mTwTm** [comment]
Fixed in #419

**Comment by cssjh** [comment]
**Verified** on 702
