### ISSUE TITLE
Disable `Search Privately` or at least change the string

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/Zerda#429]
Like focus, we're showing `Search Privately` in the context menu after text selection. We either disable this or change the text to not confuse our users.

![device-2017-08-28-145402](https://user-images.githubusercontent.com/6755074/29762374-caeb4e44-8c00-11e7-82af-3d38618d4465.png)

**Comment by idiotmax** [comment]
@harly21: How about "Turbo Search"

**Comment by harly21** [comment]
After discussing with the team, it is decided to disable "Search Privately"

**Comment by Conjuror** [comment]
[Triage] UX to decide terminology for it

**Comment by harly21** [comment]
Suggest string to be modified to "Search in Firefox Rocket"

**Comment by idiotmax** [comment]
Closed by #703

**Comment by Conjuror** [comment]
build 972
