### ISSUE TITLE
use toast instead of snackbar for "turbo mode", "block image", "clear cache", "settings clear browsing data", "download notifications"

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Zerda#455]

**Comment by FlyTori** [comment]
### List of Snack bar / Toast

**DOWNLOAD**
"file_name downloaded" (snack bar - action: OPEN)
"file_name was deleted" (snack bar - action: UNDO)
"Download started.." (toast)
"Download started.." (toast)
"Cannot find the file" (toast)
"Can’t detect SD card, file is saved to internal storage" (toast)
"SD card detected, file will be saved to SD card" (toast)
"SD card storage space is running out, file is saved to internal storage" (toast)

**SCREENSHOT**
"Screenshot saved" (snack bar - action: SHARE)

**MENU**
""Turbo mode" enabled" (toast)
""Turbo mode" disabled" (toast)
"Block website images" (toast)
"Unblock website images" (toast)
"30.2MB cache was cleared" (toast)

**SETTINGS**
"Browsing data was cleared" (toast)

Spec updated here:
https://drive.google.com/drive/folders/0B4dMhI4hp32OZHVUUHk0OElFbU0?usp=sharing

**Comment by Jacklin-ux** [comment]
SCREENSHOT VIEWER
"Screenshot deleted" (toast)

**Comment by dakaizou** [comment]
See meta issue #623
