### ISSUE TITLE
change wording from 'removable storage' to 'sd card'

### ISSUE THREAD

**Issue by walkingice** [mozilla-tw/Zerda#457]
Currently we are using 'removable storage', and we are going to change related wording to 'sd card' to follow designer's suggestion.

**Comment by Jacklin-ux** [comment]
We will update ux spec and use "SD card" instead of "removable storage". 
Thanks

**Comment by dakaizou** [comment]
See Meta #623

**Comment by dakaizou** [comment]
verified in meta issue
