### ISSUE TITLE
[Smoke Test] Screenshot animation didn't show up/ is broken

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#474]
Build 642.
DuT: Advan

After a series of operations, screenshot animation didn't show up or was broken.
I'll try to see if I can get the broken style image.

**Comment by Conjuror** [comment]
DuT: Andromax, Mito, Sansung

On Above devices, we'll have a chance around 10%~30% to run into the same issue.

**Comment by Conjuror** [comment]
![screenshot_error](https://user-images.githubusercontent.com/1625148/29852202-601ae3a6-8d6b-11e7-9a17-5ac6546e34e9.png)

**Comment by mTwTm** [comment]
@Conjuror let me know if this still happens with new implementation.

**Comment by chianger** [comment]
monitoring

**Comment by chianger** [comment]
No longer reproducible. WORKSFORME

**Comment by Conjuror** [comment]
Verified as we cannot reproduce it anymore.
