### ISSUE TITLE
Open webpage from History and press back will exit Zerda

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#480]
STR:
1. Launch Zerda
2. Go to History and tap on a history website
3. Press back key

Expected Result:

3. Back to previous page (Home in the case)

Actual Result:

3. Exit Zerda

**Comment by mTwTm** [comment]
The same happens when using the long screenshot viewer

**Comment by dakaizou** [comment]
Doing this will also clear the browsing stack
Build: 623
DuT: Sony Z3C

**Comment by idiotmax** [comment]
this.mediator.showBrowserScreen(payload.toString(), false);

**Comment by dakaizou** [comment]
verified in build 950
