### ISSUE TITLE
Mito crashes when there is no SD card and we try to download

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/Zerda#483]
Current investigation shows that Environment.getExternalStorageDirectory() is returning the SDcard path so this will lead to some problems.

**Comment by chianger** [comment]
crashes when relocation service runs.

**Comment by walkingice** [comment]
https://github.com/mozilla-tw/Zerda/commit/b4cf638187f942fc8ab55a02d8b153bab1596d3e#diff-01dafb3fd0217441330103cfc8300094R270

added a string for for canceled download.

**Comment by FlyTori** [comment]
@walkingice After consulting with Joe and Harly. The toast message would be 
**Storage inaccessible. Download cancelled.**

**Comment by dakaizou** [comment]
@FlyTori @walkingice Shall we replace "cancelled" with "canceled" to be consistent with the original UX spec(3. Download Panel - Overview)?

**Comment by dakaizou** [comment]
verified in build 1412 RC 1
