### ISSUE TITLE
Visiting website once might be recorded more than once in history

### ISSUE THREAD

**Issue by dakaizou** [mozilla-tw/Zerda#490]
STR:
1. Visit [www.google.com](https://www.google.com) (Note: not [www.google.com.tw](https://www.google.com.tw/))
1. Clear browsing history
3. Tap Home
2. Visit [www.google.com](https://www.google.com) again
3. After page is loaded, check history, there'll be two items, one of the favicons will be Globe

Note: If changing first website (in step 1) to [youtube.com](https://www.youtube.com), youtube.com will be recorded in step 5.

STR:
1. Clear browsing history
2. Visit [privacy.google.com](https://privacy.google.com)
3. Don't do anything, wait til the hashtag appears in the url
4. Check browsing history, there'll be three items, two of the favicons will be Globe

STR:
1. Clear browsing history
2. Visit [vik.kompas.com](http://vik.kompas.com/)
3. After the page is loaded, slide down the page, til the hashtag appears
4. Check history

Looks like most of the changes of the url bar are recorded in history, even when there's no http request

Might be related to #427 
Build: 636
DuT: Samsung, vibe

**Comment by Conjuror** [comment]
Suggest to P1 the issue

**Comment by mTwTm** [comment]
Result of studying the issue: https://stackoverflow.com/a/46298285/3591480

**Comment by mTwTm** [comment]
We're solving the part when one request is falsely double counted, but different links may still be recorded as separate entries.

**Comment by dakaizou** [comment]
verified in build 1124
