### ISSUE TITLE
(visual alignment) HomePanel (TopSites page)

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/Zerda#496]

**Comment by mTwTm** [comment]
Per talk with @idiotmax, I'll take this one.

**Comment by mTwTm** [comment]
#456 and #217 should cover everything for now.

**Comment by mTwTm** [comment]
Most is covered in #616. Last mile would be top site alignment.

**Comment by mTwTm** [comment]
Regression due to this alignment: #640

**Comment by Conjuror** [comment]
build 972
