### ISSUE TITLE
 (visual alignment) Menu

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/Zerda#499]

**Comment by mTwTm** [comment]
including panel

**Comment by chianger** [comment]
need to take a look on different devices  (screen size).

**Comment by mTwTm** [comment]
Comment from @carol-mozilla : Need to adjust the size of more button "..." in history and download

**Comment by carol-mozilla** [comment]
Please update "Turbo mode" icon: https://drive.google.com/open?id=0B-9PIePlQZRldEtWWlJ2ZkRCd1U
Thanks!!

**Comment by mTwTm** [comment]
@carol-mozilla : Change the trash too.

**Comment by carol-mozilla** [comment]
![screen shot 2017-09-07 at 2 51 17 pm](https://user-images.githubusercontent.com/6700296/30149907-09d7d2fc-93dc-11e7-8bd5-a319955987ee.png)
action tool bar height should be 48x48 dp!

**Comment by Conjuror** [comment]
build 972
