### ISSUE TITLE
[Function] Error messages

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/Zerda#50]

**Comment by harly21** [comment]
Carol has released the visual spec for error message: https://drive.google.com/open?id=0B-9PIePlQZRlSHVZSEhCWkhldmc

**Comment by fangshih** [comment]
After work on measurements with @walkingice offline. The final output looks pretty sharp. Good to go. : ) 
![n5_1024-1](https://user-images.githubusercontent.com/4862573/30266985-adb36514-9713-11e7-9042-4b608afbb121.png)

**Comment by Conjuror** [comment]
Good in build 972
