### ISSUE TITLE
(visual alignment) AboutPage

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/Zerda#501]

**Comment by chianger** [comment]
visual: about page background color should align with setting page.
@joechengla , will need the wordings.

**Comment by chianger** [comment]
design is uploaded (UX spec)

**Comment by carol-mozilla** [comment]
Please change the about page to light theme : White bg with black text

**Comment by Ben-YPLai** [comment]
@carol-mozilla Just like Settings Page?  I think "Your Rights Page" need to change, too?

**Comment by idiotmax** [comment]
Visual review

**Comment by Conjuror** [comment]
Build 972
