### ISSUE TITLE
(visual alignment) ScreenshotViewer

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/Zerda#502]

**Comment by chianger** [comment]
may consider a waiting cursor for loading big screenshot.

**Comment by chianger** [comment]
visual commented about color adjustment for the bottom tool bar

**Comment by chianger** [comment]
Waiting for visual to upload updated spec.
Max, please also put this into sprint planning with Fable.

**Comment by carol-mozilla** [comment]
Please update the screenshot viewer tool bar UI color: https://drive.google.com/open?id=0B-9PIePlQZRlNUVWUkk4YmxwQ2c 
spec p.18

**Comment by idiotmax** [comment]
@joseph-yar @hartsu 
redmine->File->Zerda_visual spec.pdf.pdf - 0.3.2 (12.968 MB) Delete max liu, 2017-09-05 15:22

**Comment by mTwTm** [comment]
Comment from @carol-mozilla : New viewer color (as mentioned above) and #478 add a place holder for empty item.

**Comment by carol-mozilla** [comment]
added a disabled state for the tool bar actions based on the UX change : https://drive.google.com/open?id=0B-9PIePlQZRlNUVWUkk4YmxwQ2c

**Comment by Conjuror** [comment]
build 972
