### ISSUE TITLE
[Smoke Test] Press back while on a website launched by screenshot viewer will quit the app

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#515]
Build 653

Prerequisite: 
- Screenshots in Zerda

STR:
1. Launch Zerda and visit any website
2. Tap on Menu
3. Tap on Screenshots
4. Tap on a screenshot and launch the viewer
5. Tap on "Open webpage" icon
6. Press System Back Key

Expected Result:

6. Back to website visited at Step 1

Actual Result:

6. Back to System Home

**Comment by Conjuror** [comment]
Label UX&VD to decide expected behavior for back key

**Comment by Jacklin-ux** [comment]
Agree.
Please follow expected result: Back to website visited at Step 1
Thank you

**Comment by Conjuror** [comment]
Verified on build 1072
