### ISSUE TITLE
[Smoke Test] Fail to take screenshot on vik.kompas.com with Vibe A

### ISSUE THREAD

**Issue by dakaizou** [mozilla-tw/Zerda#516]
![screenshot](https://lh3.googleusercontent.com/-8oXUz9TQees/Wai8ZQTvVGI/AAAAAAAAASM/XCWrfzr51RY8S27Ir4dOuAccePhrhszFwCL0BGAYYCw/h800/7935230824076567862%253Faccount_id%253D1)
Build: 653
DuT: Lenovo Vibe A

**Comment by cssjh** [comment]
Also failed to capture on http://android-studio.org/.
**DuT:** Advan, Andromax, Samsung

**Comment by dakaizou** [comment]
[https://www.wsj.com/asia](https://www.wsj.com/asia)
Build: 701
DuT: Samsung

**Comment by dakaizou** [comment]
verified in build 1072
