### ISSUE TITLE
[Smoke Test] Application url recorded in history

### ISSUE THREAD

**Issue by dakaizou** [mozilla-tw/Zerda#520]
Not sure if this is a bug: the application url is also recorded in history
STR:
1. Visit [tribunnews.com](http://www.tribunnews.com)
2. Tap any news below
3. Tap the whatsapp icon on the page
4. Check history, there will be whatsapp://send?...

![screenshot](https://lh3.googleusercontent.com/-xjMbur0Heic/WajFFSFJ32I/AAAAAAAAAS4/6HWigPfkf6UAf_5tpinvBk0rXUoQxMSUQCL0BGAYYCw/h854/6913708292704362017%253Faccount_id%253D0)
Build: 653
DuT: Advan, Lenovo

**Comment by mTwTm** [comment]
Related to #271

**Comment by Conjuror** [comment]
QAwanted if reproducible.

**Comment by chianger** [comment]
@dakaizou

**Comment by dakaizou** [comment]
It's not reproducible. Let's close this
