### ISSUE TITLE
[Smoke Test] Exits after tapping on Downloads

### ISSUE THREAD

**Issue by cssjh** [mozilla-tw/Zerda#521]
**STR**
1. Download a larger image (unsplash.com or NASA high resolution photos for instance)
2. Tap on Menu
3. Tap on Downloads
4. Back to system home screen
5. Downloads won't work until user clears app data

**DuT:** Andromax, Lenovo
**Build:** 653

**Comment by mTwTm** [comment]
Interesting, not sure if there should be any crash log in this scenario?

**Comment by mTwTm** [comment]
Duplicate to #518

**Comment by cssjh** [comment]
**Verified** as duplicated
