### ISSUE TITLE
Can't download file from a link

### ISSUE THREAD

**Issue by Jacklin-ux** [mozilla-tw/Zerda#530]
I go to the site below then press a link to download the file, Firefox Rocket shows "Download started...", but there is no download progress on the notification bar?
https://www.thinkbroadband.com/download

I tried the link by fennec, it works.

My device is Pixel XL

**Comment by Jacklin-ux** [comment]
I can download the file on just updated version, so please close the issue.
Thank you

**Comment by cssjh** [comment]
**Verified** on build 702
