### ISSUE TITLE
Search engine setting

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Zerda#541]
Let's follow our Desktop settings and use Google as default
https://dxr.mozilla.org/mozilla-central/source/browser/locales/search/list.json
    "id": {
      "default": {
        "visibleDefaultEngines": [
          "google", "yahoo-id", "ddg", "wikipedia-id"
        ]
      }
    },

**Comment by mTwTm** [comment]
This should apply to all language setting

**Comment by Conjuror** [comment]
see also #544

**Comment by cssjh** [comment]
**Verified** on 1072.
