### ISSUE TITLE
[Smoke Test] "Screenshot saved" & share snack bar is blocked by capture animation

### ISSUE THREAD

**Issue by cssjh** [mozilla-tw/Zerda#552]
As title.
**DuT:** Advan
**Build:** 702

**Comment by Conjuror** [comment]
This should be a correct call. However, loop UX to confirm the behavior.

**Comment by harly21** [comment]
This is not the expected behavior, snack bar should appear after the animation is completed.

**Comment by Conjuror** [comment]
Remove UX&VD per Harly's feedback. Put to triage for engineering work

**Comment by cssjh** [comment]
**Verified** on 1178.
