### ISSUE TITLE
[Smoke Test] Screenshots of sites with sticky navbar 

### ISSUE THREAD

**Issue by cssjh** [mozilla-tw/Zerda#553]
Navigate to the half of the site (http://m.slashdot.org/story/330789 for example) and capture a screenshot, the navbar will block site content in the outcome.

**DuT:** Advan
**Build:** 702

**Comment by mTwTm** [comment]
We screenshot whatever the user is seeing now, so probably a won't fix with current implementation.

**Comment by chianger** [comment]
won't fix
