### ISSUE TITLE
[Smoke Test] Screenshot animation doesn't disappear when it fails to capture

### ISSUE THREAD

**Issue by dakaizou** [mozilla-tw/Zerda#554]
Only happens on Samsung when capturing [wsj.com/asia](https://www.wsj.com/asia).
Other websites and devices seem working fine.

Build: 702
DuT: Samsung, Andromax, Lenovo
Reproduce rate: 100%

**Comment by mTwTm** [comment]
Can reproduce with onemilescroll.com
