### ISSUE TITLE
[Smoke Test] Screenshot capture animation repeats

### ISSUE THREAD

**Issue by cssjh** [mozilla-tw/Zerda#556]
It occasionally comes with *Scissors -> Check -> Check* or sometimes *Scissors -> Check -> Scissors -> Check -> Scissors -> Check*...

**DuT:** Advan, Lenovo on http://wsj.com/, Samsung
**Build:** 702

**Comment by chianger** [comment]
should be fixed together #559

**Comment by dakaizou** [comment]
verified in build 1512
