### ISSUE TITLE
There should be no icon in address bar when a site is still loading (?)

### ISSUE THREAD

**Issue by cssjh** [mozilla-tw/Zerda#567]
![screen shot 2017-09-04 at 5 02 10 pm](https://user-images.githubusercontent.com/8446577/30019350-d514e7e4-9192-11e7-9fce-4253cab9e7d3.png)
As title.
**Build:** 702

**Comment by Conjuror** [comment]
@harly21 Can someone from UX to confirm the behavior?

**Comment by Jacklin-ux** [comment]
To align fennec design, show global icon when a site is loading.
![image](https://user-images.githubusercontent.com/22672569/30042732-ba612f5a-9225-11e7-8b81-b93e25c3a203.png)

I have updated the spec as above, so please close this bug.
Thank you

**Comment by Conjuror** [comment]
Thanks for the amazing prompt reply!!!
