### ISSUE TITLE
Unable to view detailed car photos on Yahoo auto Taiwan

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Zerda#573]
https://tw.mobi.yahoo.com/autos/new-cars/trim/mazda-3-4d-2018-2-.-0%E8%B1%AA%E8%8F%AF%E9%80%B2%E5%8C%96%E7%89%88

**Comment by Conjuror** [comment]
Works for me on Pixel w/ Turbo mode: on; Block image: off

DuT: Pixel
Build 724

![mazda3](https://user-images.githubusercontent.com/1625148/30041856-e06a0ea2-921f-11e7-9fe8-9acd9aee3d19.png)

**Comment by Conjuror** [comment]
@joechengla what's your device and build?

**Comment by Conjuror** [comment]
STR:
1. Go to the page above, and click on the picture

Expected Result:
1. Show the big picture

Actual Result:
1. No picture is displayed.

**Comment by chianger** [comment]
it's mix content. the picture is not covered under SSL.
similar to #232

**Comment by Conjuror** [comment]
dup to #232

**Comment by dakaizou** [comment]
Remove QAwanted since verified
