### ISSUE TITLE
Unable to capture Google returned search page properly 

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Zerda#574]

**Comment by chianger** [comment]
Actual result: shows a black image

**Comment by chianger** [comment]
for Yahoo search it's working fine.

**Comment by cssjh** [comment]
**Verified** on 943

**Comment by mTwTm** [comment]
Note: this is fixed because we changed are user agent and is seeing a (old)webview compatible version. this problem will be back if we changed to the more modern search result page and UX is expecting this to happen.
