### ISSUE TITLE
Automatically redirect from www.pinterest.com

### ISSUE THREAD

**Issue by dakaizou** [mozilla-tw/Zerda#578]
When visiting [pinterest.com](https://www.pinterest.com), the page can't finish loading, redirecting users to pinterst://open... instead. 

Build: 724
DuT: Advan, Lenovo

**Comment by chianger** [comment]
For device with pinterest app installed, it works ok to hand over user to that app.
For cases w/o the pinterest app installed, the hand over fails so this redirect page shows up.

**Comment by Conjuror** [comment]
Open Yahoo Mail/Shopping/Store from Yahoo homepage will display "webpage not available"

**Comment by chianger** [comment]
there will be a new toast message like "The address wasn’t understood. You might need to install other software to open this address." 
@harly21 this is new string that needs review.

**Comment by chianger** [comment]
Just tested tw.mobi.yahoo.com => click on the mail button to go to yahoo mail
[Note: the DUT has no yahoo mail app installed]
Zerda (build972): display error page "webpage not available";  URL bar shows (ymail://mail)
Focus: display error page "the address wasn't understood"; URL bar shows (ymail://mail)
Chrome: goes to mobile website correctly
Fennec: goes to mobile website correctly
Chrome/

**Comment by harly21** [comment]
Could we use the current error page and change the text below rather than displaying a toast? The reason we ask is that toast only displays for a short period of time and users might miss it.

**Comment by harly21** [comment]
After discussion with Max and Wesly, it is decided that we will use the error page to display the string "The address wasn’t understood. You might need to install other software to open this address." instead of using a toast.

**Comment by cssjh** [comment]
**Verified** on 1105.

**Comment by mTwTm** [comment]
Pinterest don't redirect at home page now. Same for yahoo links, one can use https://www.pinterest.com/explore/cats/ instead as of now.
