### ISSUE TITLE
Search suggestion should only depend on user's input

### ISSUE THREAD

**Issue by dakaizou** [mozilla-tw/Zerda#579]
Now it depends on the whole text (including autocompleted text)

Build: 724
DuT: Advan, Lenovo

**Comment by idiotmax** [comment]
Please provide more specific STR or example and screenshot.

**Comment by mTwTm** [comment]
@idiotmax I think I'll take this one, thanks @joseph-yar .

**Comment by dakaizou** [comment]
![first](https://lh3.googleusercontent.com/-TNCtU5cRi9Y/WbIBGYVWNUI/AAAAAAAAAgE/MIqRTHTgtkwjoccfC4fcbIukKCo7u5Y2wCL0BGAYYCw/h854/5011570715808167125%253Faccount_id%253D0)
![second](https://lh3.googleusercontent.com/-83iziG5R3go/WbIBF7ZexfI/AAAAAAAAAfw/7cXUu6zrtL0apJDW9a5BCXYAlw1cLGs3gCL0BGAYYCw/h854/1300270919730057869%253Faccount_id%253D0)
![third](https://lh3.googleusercontent.com/-oBS3t_UuRU0/WbIBFBmlxjI/AAAAAAAAAfg/DkcFiFF-N2c0B3EV__S006g_Ldge1ZcIQCL0BGAYYCw/h854/8988932578138968944%253Faccount_id%253D0)

Search suggestions in the first screenshot should be like the second instead of the third

Build: 855
DuT: Advan

**Comment by cssjh** [comment]
**Verified** on 1050.
