### ISSUE TITLE
[Function] Setting->Clear browsing data

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/Zerda#58]

**Comment by Conjuror** [comment]
Not sure why to close this issue. It's not implemented yet on build 471 (Daily build on Aug 23rd), neither see any commits related to it by now.

Would you mind to point out the related commits if I missed it, @idiotmax ? Thank you for kindness.

**Comment by chianger** [comment]
Able to clear "browsing history", "cookies", "cache".
A snackbar will show up after user clears data.

**Comment by chianger** [comment]
needs UX (Jack/Tori) to confirm the snack bar message.

**Comment by Jacklin-ux** [comment]
The snackbar message would be "Browsing data was cleared", when Cache option is unchecked.
I will update this to the spec

**Comment by chianger** [comment]
The snackbar message would be "Browsing data was cleared", (P1)
; when Cache option is unchecked, I will update this to the spec (P2)

**Comment by chianger** [comment]
Looks like it's working already!

**Comment by mTwTm** [comment]
We still need remove cache implementation

**Comment by chianger** [comment]
as removing cache is merged.

**Comment by Conjuror** [comment]
Build 972
