### ISSUE TITLE
Filenames of downloads should be renamed as download manager handling

### ISSUE THREAD

**Issue by dakaizou** [mozilla-tw/Zerda#584]
In accordance with UX spec 2-7-3 (save image)

Build: 724
DuT Advan, Andromax

**Comment by chianger** [comment]
Actual result: android system handles the rename and didn't replace file (which is fine). but download panel doesn't display the file

**Comment by chianger** [comment]
QAWanted to confirm the expected result and likely the title needs to be changed.

**Comment by Conjuror** [comment]
According to current behavior, download manager will rename the file. However, file names in download panel are still displayed as the origin one.

We should have download panel displays the correct one which is the same as the file names in file system.

**Comment by dakaizou** [comment]
STR:
1. Visit [youtube.com](https://www.youtube.com)
2. Long tap any profile picture
3. Save image
4. Repeat step 2 and 3
5. Check Downloads (there will be two images both named "photo.jpg")
Note: the images should be rename as photo-1.jpg, photo-2.jpg from the second one onward to match file names in the system
![screenshot](https://lh3.googleusercontent.com/-2gcZePx8-d4/WbC3qMAUZiI/AAAAAAAAAbc/hcF6kIHoUbk5ru6mPq30XeObgpn9jQdUwCL0BGAYYCw/h1920/1596120693906215309%253Faccount_id%253D3)
![screenshot](https://lh3.googleusercontent.com/-Hgk6X6tzj2s/WbC48KqT0KI/AAAAAAAAAcQ/SrdQHZd6l8YglRzFHonNas_VHlf9wwdZACL0BGAYYCw/h1920/3234449830267041462%253Faccount_id%253D3)
Build: 790
DuT: Samsung

**Comment by Conjuror** [comment]
Removed QAWanted as STR provided. Thanks to @dakaizou

**Comment by dakaizou** [comment]
verified in build 943
