### ISSUE TITLE
[dogfooding] Top site ranking mechanism should be refined

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#586]
Top site ranking doesn't seem to work (all Yahoo on Joe's screen)

Build 724

**Comment by mTwTm** [comment]
We're tripling the count since we insert in onReceivedIcon and onPageFinished

**Comment by mTwTm** [comment]
onPageFinished is also fired twice or 4 times as much as onPageStarted

**Comment by mTwTm** [comment]
09-06 15:05:48.368 9254-9254/org.mozilla.zerda.debug.tyu E/mTwTm: 260879366 - onPageStarted, url: https://m.youtube.com/
09-06 15:05:48.368 9254-9394/org.mozilla.zerda.debug.tyu E/libEGL: validate_display:99 error 3008 (EGL_BAD_DISPLAY)
09-06 15:05:48.843 9254-9254/org.mozilla.zerda.debug.tyu E/mTwTm: 260879366 - onPageFinished, url: https://m.youtube.com/
09-06 15:05:49.008 9254-9254/org.mozilla.zerda.debug.tyu E/mTwTm: 260879366 - onPageFinished, url: https://m.youtube.com/
09-06 15:05:50.760 1336-1352/? E/ReloadingLock: Finalizing LOCKED Token[shortcuts 2017-09-06 15:05:37.138]
09-06 15:05:55.144 639-673/? E/ANDR-PERF-OPTSHANDLER: Warning: Resource [2, 0] not supported for core 1. Instead use resource for core 0
09-06 15:05:55.144 639-673/? E/ANDR-PERF-RESOURCEQS: Failed to apply optimization [2, 2, 0]
09-06 15:05:55.198 9254-9254/org.mozilla.zerda.debug.tyu E/RecyclerView: No adapter attached; skipping layout
09-06 15:05:57.069 9254-9254/org.mozilla.zerda.debug.tyu E/RecyclerView: No adapter attached; skipping layout
09-06 15:05:57.322 9254-9254/org.mozilla.zerda.debug.tyu E/mTwTm: 250587576 - onPageFinished, url: https://m.youtube.com/
09-06 15:05:57.330 9254-9254/org.mozilla.zerda.debug.tyu E/mTwTm: 250587576 - onPageFinished, url: https://m.youtube.com/
09-06 15:05:57.344 9254-9254/org.mozilla.zerda.debug.tyu E/mTwTm: 250587576 - onPageStarted, url: https://m.youtube.com/
09-06 15:05:57.618 9254-9254/org.mozilla.zerda.debug.tyu E/mTwTm: 250587576 - onPageFinished, url: https://m.youtube.com/
09-06 15:05:57.659 9254-9254/org.mozilla.zerda.debug.tyu E/mTwTm: 250587576 - onPageFinished, url: https://m.youtube.com/

**Comment by mTwTm** [comment]
In #632, we fixed in ae44fca additional events when is resource is loaded and in d4ee9ac some unwanted onPageFinished events. However, we still record redirect pages which is tracked in #360, so let's close this issue.

**Comment by dakaizou** [comment]
verified in build 790
