### ISSUE TITLE
[dogfooding] Screenshot info says time but only shows date

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#589]
as title

Build 724

**Comment by chianger** [comment]
expected behavior: showing complete date+time.

**Comment by chianger** [comment]
@mTwTm Jack (UX) confirmed with me that the UX decision was given.
We'll want to replace "time" with "date", and literally showing date only.

So the only change needed here is to replace the word.

**Comment by dakaizou** [comment]
Let's track this in meta #950
