### ISSUE TITLE
[dogfooding] Not sure about "open URL" icon in screenshot viewer 

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#593]
as title

**Comment by carol-mozilla** [comment]
please try "link" icon: https://drive.google.com/open?id=0B-9PIePlQZRlOXhnc2xVcTgxbTA

**Comment by chianger** [comment]
need a new icon

**Comment by harly21** [comment]
Carol has delivered the new icon in her comment

**Comment by idiotmax** [comment]
@joseph-yar:  svg: openinbrowser.xml

**Comment by cssjh** [comment]
**Verified** on 943.
