### ISSUE TITLE
[dogfooding] color theme follow up

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#600]
System theme color : text selected color/ dialogue /Settings/ choices

**Comment by Conjuror** [comment]
block #285

**Comment by mTwTm** [comment]
Screen shot from Carol:
![screenshot_2017-09-05-11-46-46](https://user-images.githubusercontent.com/6755074/30049640-03afbbb8-924e-11e7-876c-623a1cf4abca.png)
This is invalid, this is the color of IME and is configured by Z3C theme
![screenshot_2017-09-05-11-23-30](https://user-images.githubusercontent.com/6755074/30049638-0398e9ec-924e-11e7-934c-8d6d15f71c88.png)
We should change this.
![screenshot_2017-09-05-11-22-25](https://user-images.githubusercontent.com/6755074/30049639-039c15ea-924e-11e7-91b0-93a2645851b4.png)
This is invalid, this is the main color of Z3C and is unconfigurable.

**Comment by cssjh** [comment]
Dup
Meta #628

**Comment by carol-mozilla** [comment]
- All the highlight color please change to #0a84ff
- Text Highlight fill: #0a84ff ,opacity: 30%
