### ISSUE TITLE
block non-http/https download links

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/Zerda#605]
Releated to #522 we should at least first block the crashing.

**Comment by mTwTm** [comment]
dup #341

**Comment by mTwTm** [comment]
Re-open this since we'll first block non-http/https urls but still investigate ways to download those.

**Comment by cssjh** [comment]
**Verified** on 1072.

**Comment by FlyTori** [comment]
After consulting with Joe, the toast message should be "Download protocol not supported."
