### ISSUE TITLE
[Smoke Test] Search "clear input" doesn't clear autocomplete text for the first tap

### ISSUE THREAD

**Issue by dakaizou** [mozilla-tw/Zerda#610]
STR:
1. Tap search bar or search button or url
2. Type something for showing autocomplete text (e.g. "mo")
3. Tap clear input button at the end

Expected result:

4. Input cleared

Actual result:

5. Input selected, suggestions cleared

Build: 751
DuT: Andromax, Samsung

**Comment by mTwTm** [comment]
Escalate to P1 since severity changed due to fixing of other bugs.
