### ISSUE TITLE
[Smoke Test] Onboarding content is a bit more than a page

### ISSUE THREAD

**Issue by dakaizou** [mozilla-tw/Zerda#615]
![screenshot](https://lh3.googleusercontent.com/-QzujYfG2eKE/Wa9acNu_U4I/AAAAAAAAAXI/TLA0wy_7tPYvRrQKaYea68KgG4bbkRzqACL0BGAYYCw/h854/2670590289985521851%253Faccount_id%253D2)

Build: 751
DuT: Andromax, Samsung

**Comment by cssjh** [comment]
![err](https://user-images.githubusercontent.com/8446577/30092407-55de0ab8-92f1-11e7-9a71-d00cf684f662.png)
This appears after scrolling down.

**Comment by Conjuror** [comment]
Wait for Visual to input

**Comment by walkingice** [comment]
It should be fixed now

**Comment by dakaizou** [comment]
Looks good in build 790

**Comment by dakaizou** [comment]
Verified in build 790

**Comment by Conjuror** [comment]
Removed QAWanted as it's verified.
