### ISSUE TITLE
Improve title guessing from domain

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/Zerda#624]
We don't want to show just "h" when we only for domain. We should try to guess the most important part.

**Comment by chianger** [comment]
another dup created #734 during dogfooding.

**Comment by idiotmax** [comment]
@Ben-YPLai  FYI
http://www.supermind.org/blog/1078/extracting-second-level-domains-and-top-level-domains-tld-from-a-url-in-java

**Comment by mTwTm** [comment]
@Ben-YPLai FYI
https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/java/org/mozilla/focus/shortcut/IconGenerator.java

**Comment by mTwTm** [comment]
Try aloodo.org to find a page without title

**Comment by cssjh** [comment]
@mTwTm Tried aloodo.org test but not sure if this is expected:

![aloodo](https://user-images.githubusercontent.com/8446577/30577710-a5808036-9d42-11e7-86f9-326e3abc95d7.png)

**Comment by mTwTm** [comment]
Replied on #843

**Comment by cssjh** [comment]
**Verified** on 1178.
