### ISSUE TITLE
Missing top site on small devices will make other elements fall down

### ISSUE THREAD

**Issue by dakaizou** [mozilla-tw/Zerda#640]
STR:
1. Visit any page
2. Tap Home button
3. Search bar is at the bottom for a while

STR:
1. Delete all top site

![screenshot](https://lh3.googleusercontent.com/-_B12yfUQ2sU/WbCwvfxmBuI/AAAAAAAAAas/MKp4I0qUN7se_QSNguuUkd6og52DWEgCACL0BGAYYCw/h854/6876170721238670156%253Faccount_id%253D2)

Build: 790
DuT: Andromax, Advan

**Comment by mTwTm** [comment]
Hahahaha my fault I'll take this one. give minsize for topsite panel

**Comment by dakaizou** [comment]
verified in build 855
