### ISSUE TITLE
The icons on empty panel of My shots should use grey color 

### ISSUE THREAD

**Issue by Jacklin-ux** [mozilla-tw/Zerda#641]
This bug is about visual design. 
Currently, the icons on empty panel of Downloads/History use grey color, so the design should be aligned.
![screenshot_20170907-103756](https://user-images.githubusercontent.com/22672569/30143655-a4d3cc5c-93b9-11e7-9beb-97ac9e84d396.png)

**Comment by dakaizou** [comment]
See meta issue #628

**Comment by dakaizou** [comment]
verified in meta issue
