### ISSUE TITLE
After deleting screenshot image, screenshot preview still exists on "My shots"

### ISSUE THREAD

**Issue by FlyTori** [mozilla-tw/Zerda#642]
Actual result: 
1. delete screenshot image
2. return to "My shots" panel
3. the deleted screenshot preview still on the panel

Expected result
1. delete screenshot image
2. return to "My shots" panel
3. the deleted screenshot should be removed from "My shots" panel

Build: 0.4.790.beta

**Comment by dakaizou** [comment]
verified in build 943
