### ISSUE TITLE
location prompt shows up every time if you use news.google.com

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Zerda#644]
it's a big usability problem as the prompt is in your face every time, such as you read one news article and go to the main google news page to read the next news article

can we explore either not having the prompt being in your face in the middle of the screen?
or remember the choice for the session

**Comment by Conjuror** [comment]
Currently, we reload permission every time. This is expected.

**Comment by chianger** [comment]
we can triage this but it was a P2 feature per our discussions weeks ago.

**Comment by joechengla** [comment]
yes but the experience can be improved i think
it is actually very annoying

**Comment by joechengla** [comment]
let's discuss priority. it's making our browser having a bad UX

**Comment by Conjuror** [comment]
dup #735

**Comment by chianger** [comment]
dup #735
