### ISSUE TITLE
Missing top sites should be filled in with default when reopening Zerda

### ISSUE THREAD

**Issue by dakaizou** [mozilla-tw/Zerda#646]
STR:
1. Remove top site
2. Repeat step 1 til only 7 top sites left
3. Reopen Zerda

There should be 8 top sites when reopening Zerda. It should be something like CLEAR BROWSING HISTORY as resolved in #475 

Build: 790
DuT: Andromax, Advan, Samsung

**Comment by idiotmax** [comment]
This is not described in our spec. In the previous conversion with UX, we will reset topsite only when clearing the whole history, including from Settings or History Panel. @Conjuror ?

**Comment by Conjuror** [comment]
Verified as invalid.

**Comment by Conjuror** [comment]
Verified as invalid.

**Comment by dakaizou** [comment]
Remove QAwanted since verified
