### ISSUE TITLE
The title of "Support", "Your Rights" or "Privacy Notice" pages should be the same as its name

### ISSUE THREAD

**Issue by Jacklin-ux** [mozilla-tw/Zerda#648]
Currently, we all use "About" on the title, but we should modify the tile to "Support", "Your Rights"or "Privacy Notice" for the pages below.

![screenshot_20170907-104808](https://user-images.githubusercontent.com/22672569/30144105-bf5a9b12-93bb-11e7-9ea8-437b16b71ed1.png)
![screenshot_20170907-104759](https://user-images.githubusercontent.com/22672569/30144107-bfcd38b6-93bb-11e7-8378-915c6ac084f2.png)
![screenshot_20170907-103938](https://user-images.githubusercontent.com/22672569/30144104-bf5458ec-93bb-11e7-8838-26de5453818f.png)
*The URL will be updated, so will show correct page.

**Comment by dakaizou** [comment]
See meta issue #623
