### ISSUE TITLE
Turning off Turbo Mode in onboarding doens't work

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#652]
as title
Build 790

STR:
1. Clear App DATA
2. Launch Zerda
3. Tap Next and turn off Turbo Mode
4. Finish Onboarding pages
5. Tap on Menu

Expected Result:

3. Turbo mode is off
5. Turbo mode is off

Actual Result:

5. Turbo mode is on

**Comment by dakaizou** [comment]
verified in build 950
