### ISSUE TITLE
[Smoke Test] Deleting 4 top sites make other elements slide down a little on small devices

### ISSUE THREAD

**Issue by dakaizou** [mozilla-tw/Zerda#670]
Related to #640, not very salient but users can tell the movement

![screenshot](https://lh3.googleusercontent.com/-STjZGLegQ_s/WbH4LoFUA4I/AAAAAAAAAeQ/AtU07dmGSpwll8ARLpSBGDO6VNutxKOhwCL0BGAYYCw/h854/1158076790019536048%253Faccount_id%253D0)
![screenshot](https://lh3.googleusercontent.com/-uZxr4jae83Y/WbH4ITFsigI/AAAAAAAAAeQ/_YxPgNB59ggEblEsMPkAG0b6cuFnTJCUQCL0BGAYYCw/h854/4460007413228506533%253Faccount_id%253D0)

Build: 855
DuT: Samsung, Advan, Andromax

**Comment by mTwTm** [comment]
Hmm I'll fix this directly, removing UX&VD tag since I think it's on my side.

**Comment by dakaizou** [comment]
verified in build 1072
