### ISSUE TITLE
Update screenshot empty state UI

### ISSUE THREAD

**Issue by carol-mozilla** [mozilla-tw/Zerda#679]
please help update screenshot library empty states UI
Spec: https://drive.google.com/open?id=0B-9PIePlQZRleThmcmU1LXFKRXM

**Comment by idiotmax** [comment]
@Conjuror Please provide device screenshot and also spec page screenshot. Thanks.

@carol-mozilla @harly21 The latest asset: screenshot_empty.xml looks like this. Please update visual spec to reflect final design. Thanks.
<img width="442" alt="screenshot_empty" src="https://user-images.githubusercontent.com/441664/30379144-196d69e8-98c8-11e7-9e3f-4d78c277ad64.png">

Suggest to close #755 after clarify.

**Comment by Conjuror** [comment]
build 1072
