### ISSUE TITLE
Disable "Save downloads to" option if there is no inserted SD card or external storage device

### ISSUE THREAD

**Issue by Jacklin-ux** [mozilla-tw/Zerda#693]
I suggest we can put this issue to P1, what do you think?

**Comment by mTwTm** [comment]
Add bug label to triage this.

**Comment by Jacklin-ux** [comment]
I found #461 is the same as this issue

**Comment by mTwTm** [comment]
You really want it. Close as duplicate.

**Comment by cssjh** [comment]
**Verified** as duplicate.
