### ISSUE TITLE
Change name to Firefox Rocket

### ISSUE THREAD

**Issue by Jacklin-ux** [mozilla-tw/Zerda#697]
Please change name to "Firefox Rocket":
1.Onboarding first page title (Thanks for choosing Firefox Rocket)
2.Settings - the description of Send usage data (...improve Firefox Rocket...)
3.About - the description (Firefox Rocket is a fast...)
4.About - the description of Your Rights ("Firefox Rocket "instead of "Firefox Focus")

Thank you

**Comment by cssjh** [comment]
**Verified** on 943
