### ISSUE TITLE
Page is blank when HomeFragment is resumed

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/Zerda#700]
STR:

1. Tap a top site
2. After the page is loaded, tap home button.
3. Press back key
4. The top site url is there but the page is blank

**Comment by mTwTm** [comment]
Regression due to #632

**Comment by mTwTm** [comment]
Also regressioned and also fixed: no page history stack after #632 and before #705, every time back is clicked Firefox Rocket exits or goes back to home.

**Comment by dakaizou** [comment]
verified in build 1019
