### ISSUE TITLE
[Smoke Test] Downloading image exits Zerda

### ISSUE THREAD

**Issue by cssjh** [mozilla-tw/Zerda#723]
**STR**
1. Download an larger image (like unsplash.com or NASA high resolution images)
2. Download completes -> Zerda exits
3. Reopen Zerda
4. Open Downloads ->
4-1. Zerda exits again (Advan)
4-2. Zerda doesn't exit but Download list is empty (Andromax)
5. No crash message is shown

**DuT:** Advan, Andromax
**Build:** 950

**Comment by cssjh** [comment]
Reference: #521

**Comment by mTwTm** [comment]
2 is #718,
4-1 is #719.
Not related to #521 IMHO.

**Comment by Conjuror** [comment]
Let's use this one as a META. Assuming no patches for this one, but having one for #718 and the other one for #719 . We'll close the issue once #718 and #719 are fixed.

**Comment by WeiWW** [comment]
2<- It maybe chromium OOM, but we can't control this error.
https://bugs.chromium.org/p/chromium/issues/detail?id=525938

**Comment by mTwTm** [comment]
I propose to treat #718 and #719 as won't fix. Let's discuss this in the triage meeting.

**Comment by chianger** [comment]
won't fix
