### ISSUE TITLE
[Smoke Test] Can't open files on Downloads

### ISSUE THREAD

**Issue by cssjh** [mozilla-tw/Zerda#726]
A toast message "Cannot find the file." will show when tapping on files just downloaded.

**DuT:** Advan, Samsung
**Build:** 943

**Comment by Conjuror** [comment]
be noted that 943 is first FC build

**Comment by mTwTm** [comment]
I suppose this apply to any file type, not image only?

**Comment by dakaizou** [comment]
@mTwTm That's right

**Comment by mTwTm** [comment]
Need to fix this, quick fix would be to change from:
new File(download.getFileUri()).exists()
to
new File(new URI(download.getFileUri()).getPath()).exists()

but we will need to check if the uri is always file:// schema

**Comment by dakaizou** [comment]
verified in build 1019
