### ISSUE TITLE
[dogfooding] Block Image -> Block Images

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#732]
string refinement

**Comment by Conjuror** [comment]
According to the review comment, this is requested to confirm with Michelle.

**Comment by mTwTm** [comment]
Change assignee since Ann is already on it. https://github.com/mozilla-tw/Zerda/pull/738

**Comment by mTwTm** [comment]
ni Harly since still need to confirm with Michelle.

**Comment by FlyTori** [comment]
Just got the feedback from Michelle. She also prefers "Block images" so we can go for it.

**Comment by chianger** [comment]
replace new-string label with 'l10n'. it has been reviewed by copy reviewer but we also need l10n.

**Comment by Conjuror** [comment]
good in build 972
