### ISSUE TITLE
There is a scrollbar on Mito's onboarding page 3

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/Zerda#743]
![device-2017-09-12-165639](https://user-images.githubusercontent.com/6755074/30317801-ca5e989e-97dd-11e7-80e0-7f6e9ca4bb19.png)

Mito is 320 x 240 irrc

**Comment by fangshih** [comment]
Can we reduce the padding between the icon and the title text by half for this type of screen resolution?

**Comment by Ben-YPLai** [comment]
Verified by @fangshih
