### ISSUE TITLE
[SUMO] Need Zerda icon for support.mozilla.org

### ISSUE THREAD

**Issue by rtanglao** [mozilla-tw/Zerda#745]
We would like this icon ASAP.

Please:
1. Make it the same size as the other logos in the spritesheet here:
https://github.com/mozilla/kitsune/blob/master/kitsune/sumo/static/sumo/img/logos.large.sprite.png

2. Or give us the icon as big as possible in PNG format please :-)

Whatever is easiest for you :-) !

shadow bugzilla bug is: https://bugzilla.mozilla.org/show_bug.cgi?id=1399163

**Comment by rtanglao** [comment]
@chianger @joechengla since we are timezone challenged (SUMO team generally works in Pacific, the developer who needs the icon is in Greece, etc) can you ping the team to give us this asset ASAP pretty please :-) ?!?

**Comment by chianger** [comment]
https://drive.google.com/drive/folders/0B1V1eo-I8g3dVnpJdlJHNUpYTzg
@rtanglao
