### ISSUE TITLE
Download state not refreshed when the Downloads panel is open

### ISSUE THREAD

**Issue by dakaizou** [mozilla-tw/Zerda#751]
STR:
1. Dowload a large file
2. Tap on Menu
3. Tap on Downloads (the item is downloading)
4. Slide down system bar and turn off internet connection
5. Back to Downloads panel (it's still downloading)
6. Tap on History tab at the bottom
7. Tap on Downloads tab at the bottom (it's paused now)

Build: 955
DuT: Samsung

**Comment by mTwTm** [comment]
Possible duplicate to #125

**Comment by chianger** [comment]
dup to #125

**Comment by dakaizou** [comment]
verified since dup
