### ISSUE TITLE
[Smoke Test] Reddit.com's title is replaced by other website

### ISSUE THREAD

**Issue by dakaizou** [mozilla-tw/Zerda#774]
STR:
1. Clear app data
2. Remove all topsite
3. Visit huffpost.com
4. Tap on back key
5. Repeat step 3 and 4 until huffpost become top site
6. Visit reddit.com
7. Tap on back key
8. Repeat step 6 and 7 until the second top site appear

![screenshot](https://lh3.googleusercontent.com/---ksRLYsVnI/WbouJ0aHQkI/AAAAAAAAAoA/BwXRBh4rdZk2dlhrq7RsVWYygecqp-McwCL0BGAYYCw/h1920/7299279031824957361%253Faccount_id%253D3)
Build: 1033
DuT: Samsung

**Comment by chianger** [comment]
not always reproduce

**Comment by Conjuror** [comment]
We are looking for a more solid reproduce steps.

**Comment by mTwTm** [comment]
I've been taking care of these sort of problems so this could be fixed recently.

**Comment by Conjuror** [comment]
monitoring for a week. If QA has no way to reproduce it, close it as invalid

**Comment by chianger** [comment]
no longer reproducible.

**Comment by dakaizou** [comment]
verified as invalid
