### ISSUE TITLE
Sites using hardware acceleration can't be captured: instagram, google search result

### ISSUE THREAD

**Issue by dakaizou** [mozilla-tw/Zerda#775]
[www.instagram.com/mozillagram/](https://www.instagram.com/mozillagram/)

Build: 1033
DuT: Oppo, Samsung

**Comment by mTwTm** [comment]
Can't reproduce on Sony, is this specific device only?

**Comment by mTwTm** [comment]
Related to #574

**Comment by mTwTm** [comment]
webkitView.setLayerType(View.LAYER_TYPE_SOFTWARE, null); would be a quick fix but introduce massive performance regression.

**Comment by mTwTm** [comment]
The Google Canary webview seems good. We'll try for a temporary solution, though.

**Comment by mTwTm** [comment]
Changes layer on the fly does not work as smoothly as we hoped.

**Comment by chianger** [comment]
webview limitation so P2 it. (With latest canary it should be fixed.)

**Comment by chianger** [comment]
This is verified fix with Android System WebView update (version 61).
Suggest to have SUMO article.

**Comment by chianger** [comment]
WORKSFORME and there will be SUMO follow up tracked through bugzilla.

https://bugzilla.mozilla.org/show_bug.cgi?id=1383902
