### ISSUE TITLE
[low priority edge case] screenshot of rolandtanglao.com home page hangs Rocket

### ISSUE THREAD

**Issue by rtanglao** [mozilla-tw/Zerda#783]
Found in Firefox Rocket Nightly 0.7.1050.nightly (and this issue was also present in past builds i.e. this has never worked)

**Steps to reproduce on Google Pixel XL running September 2017 update of Android 8 Oreo:**

1. Open Firefox Rocket and surf to http://rolandtanglao.com (which is a blog home page with links to 2500 blog posts)
1. Take a screenshot  (Menu button->tap screenshot)

**Expected Result: Successful screenshot or error message**

**Actual Result: Rocket hangs**

**Comment by dakaizou** [comment]
Dup #554
