### ISSUE TITLE
Include Learn More for Turbo Mode

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Zerda#786]

**Comment by Conjuror** [comment]
Please check where to add the Link/Button.

**Comment by idiotmax** [comment]
Need the TurboMode "Learn more" URL

**Comment by Jacklin-ux** [comment]
![image](https://user-images.githubusercontent.com/22672569/30677829-c896c16e-9ec0-11e7-885a-1333dc9b8c74.png)

**Comment by chianger** [comment]
URL of  TurboMode: 
https://support.mozilla.org/1/mobile/%VERSION%/%OS%/%LOCALE%/turbo

**Comment by cssjh** [comment]
**Verified** on 1267.
