### ISSUE TITLE
[On boarding] On boarding button is overlayed with functionality buttons

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#79]
as title

**Comment by Conjuror** [comment]
https://drive.google.com/open?id=0B11T

**Comment by mTwTm** [comment]
Link seems to be broken. And I guess we should remove the onboarding if it's not going to be used.

**Comment by Conjuror** [comment]
I'd like to reference UX for removing on-boarding

**Comment by Conjuror** [comment]
Per discussion in dogfooding event, we prefer to remove FAB from on-boarding.

**Comment by dakaizou** [comment]
Verified in build 540
