### ISSUE TITLE
Initial core browser wireframe visualization

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/Zerda#8]
acceptance criteria:
Functions including cookies, URL bar, navigation, media playback, context menu (system UI for text;share/copy for hyperlinks ;share/save for images; not handling video)

dependent: #8, #23

**Comment by mTwTm** [comment]
I'm trying to dig into whatever the extra Focus cleanup steps are. I'll try to back them out if we don't need them.

**Comment by mTwTm** [comment]
![device-2017-07-27-173627](https://user-images.githubusercontent.com/6755074/28664234-45aee9b0-72f2-11e7-837f-12f3eba9d1b4.png)
![device-2017-07-27-173646](https://user-images.githubusercontent.com/6755074/28664235-45ec8e5a-72f2-11e7-9b64-6db7413a5483.png)

A very basic (But could be buggy) implementation is done. :)

**Comment by Conjuror** [comment]
verified in build 86
