### ISSUE TITLE
Too many bold characters in search suggestion box

### ISSUE THREAD

**Issue by cssjh** [mozilla-tw/Zerda#800]
When typing "moz" (3 characters) in the search bar, Zerda auto completes them with "mozilla.org" (11 characters).

Zerda also makes the first 11 characters of each suggestion bold like these:
"**mozart**", "**mozilla fir**efox", "**mozicsillag**"...

But they should be:
"**moz**art", "**moz**illa firefox", "**moz**icsillag"...

**Build:** 1050

**Comment by dakaizou** [comment]
verified in build 1124
