### ISSUE TITLE
[Smoke Test] Favicon of vimeo.com is a question mark

### ISSUE THREAD

**Issue by cssjh** [mozilla-tw/Zerda#805]
As title.

**DuT:** Andromax, Oppo
**Build:** 1072

**Comment by chianger** [comment]
@cssjh could you attach a screenshot of this "question mark"? thanks

**Comment by cssjh** [comment]
@chianger 

History panel
![pm1](https://user-images.githubusercontent.com/8446577/30527626-686ad74a-9c5d-11e7-9fc7-056b9dde48ff.png)

Top sites
![qm2](https://user-images.githubusercontent.com/8446577/30527627-68ab0a40-9c5d-11e7-929e-1213225c4331.png)

**Comment by idiotmax** [comment]
Please also verify #843

**Comment by cssjh** [comment]
**Verified** on 1178.
