### ISSUE TITLE
Crashed when downloading via link after CLEAR BROWSING HISTORY

### ISSUE THREAD

**Issue by dakaizou** [mozilla-tw/Zerda#809]
STR:
1. Clear browsing stack (Reopen the app or Tap back key until home screen)
2. Visit [http://www.coverr.co/s3/mp4/Mobile-Games.mp4](http://www.coverr.co/s3/mp4/Mobile-Games.mp4) through home screen search bar
3. Downloading toast appears
4. Tap on menu
5. Tap on history
6. Tap on CLEAR BROWSING HISTORY
7. Tap on CLEAR
8. Tap on outside the menu panel
9. Tap on app home
10. Tap on search bar
11. Visit [http://www.coverr.co/s3/mp4/Mobile-Games.mp4](http://www.coverr.co/s3/mp4/Mobile-Games.mp4) again

Build: 1072, 1033
DuT: Samsung, Advan

**Comment by dakaizou** [comment]
related to #808 #194 
fixed in build 1124

**Comment by Conjuror** [comment]
per @dakaizou 's comment, close this issue and track #858 as follow up
