### ISSUE TITLE
Deleting a custom top site makes its record in History gone

### ISSUE THREAD

**Issue by cssjh** [mozilla-tw/Zerda#815]
**STR**
1. Remove one or more default top sites
2. Visit a site for several times (yahoo.com for example) -> it becomes top site _X_
3. Delete _X_ -> it will also disappear in History

**Build:** 1072

**Comment by mTwTm** [comment]
Sort of duplicate of #349

**Comment by chianger** [comment]
need PM decision

**Comment by Ben-YPLai** [comment]
It will not disappear now.
related to 874

**Comment by chianger** [comment]
not happening anymore on build 0.8.1413
