### ISSUE TITLE
App link error page becomes top site

### ISSUE THREAD

**Issue by dakaizou** [mozilla-tw/Zerda#824]
as title, related to #595 

Build: 1105
DuT: Samsung

**Comment by idiotmax** [comment]
STR:

1. input URL and load: https://www.pinterest.com/
2. Click "Get the app" button in banner on top of the webpage to trigger "unknown schema"
3. Repeat step 2 until non-supported URL becomes one of the TopSite with URL: "pinterest://open?link_click_id=412581485618476519247659276"

**Comment by dakaizou** [comment]
verified in build 1412 RC 1
