### ISSUE TITLE
Remove Detik and replace with https://www.kaskus.co.id/

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Zerda#826]

**Comment by joechengla** [comment]
add https://www.kaskus.co.id/ as the end of the list the 8th position.

**Comment by joechengla** [comment]
next on the list is https://www.kapanlagi.com/

**Comment by Ben-YPLai** [comment]
remove Detik and add https://www.kapanlagi.com/ as the end of the default topsites list

**Comment by Conjuror** [comment]
According to the comments, the eighth should be [https://www.kasus.co.id](https://www.kasus.co.id). If a user intends to remove a TopSites from top 8, the ninth will be [https://www.kapalangi.com](https://www.kapalangi.com)

**Comment by Conjuror** [comment]
Build 1158

**Comment by joechengla** [comment]
we go with https://www.kapanlagi.com/ only if we can't get https://www.kaskus.co.id/ favicon

**Comment by chianger** [comment]
confirmed current behavior is kapanlagi
