### ISSUE TITLE
In url inputbox, if user input is same as the autocomplete search suggestions does not change

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/Zerda#828]
For instance:

On my device
userinput | autocomplete | search suggestion
m | merdeka.com | maps, mcdonalds
mo | momoshop.com.tw | movies, moana
mom | momoshop.com.tw | movies, moana <- Should be mom, momondo...
moma | x | moma, moma ps1

This happens only when the user input is the same as current suggested autocomplete.

**Comment by cssjh** [comment]
**Verified** on 1267.
