### ISSUE TITLE
[Smoke Test] Sometimes using back or forward button in settings menu doesn't work.

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#83]
Sometimes using back or forward button in settings menu doesn't work.

STR:
1. Launch App
2. Tap on search button
3. go to any website
4. tap on a link
5. tap settings button
6. tap back key or forward key
7. repeat step 5 and 6

Expect Result:
6. visit correct website

Reproduce Rate:
60%

Noted that some buttons in settings menu will also have animations, not sure if I triggered other event.

**Comment by mTwTm** [comment]
I believe it's just they're too small to be clicked. (The touch area is only the icon itself for now, unlike the buttons.) Will be changed in a newer spec.

**Comment by Conjuror** [comment]
I think @mTwTm is right. I used Samsung J7 Prime which has a larger screen and I can reproduce the issue always. Turned this into UX issue if we need to define a larger space for clicking.

**Comment by mTwTm** [comment]
Per my discussion with Carol it should be fixed. I'll make sure this is considered in the new spec.

**Comment by Conjuror** [comment]
verified in build 214
