### ISSUE TITLE
[dogfooding] Need Set Firefox Rocket as default SUMO page; (currently link to focus page)

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#830]
as title. assign to @chianger

**Comment by chianger** [comment]
URL of Set default browser:  
https://support.mozilla.org/1/mobile/%VERSION%/%OS%/%LOCALE%/rocket-default

**Comment by chianger** [comment]
current 'support' link under about page also goes to Focus'.
Should be changed to this: 
https://support.mozilla.org/1/mobile/%VERSION%/%OS%/%LOCALE%/rocket-help

**Comment by cssjh** [comment]
**Verified** on 1400.
