### ISSUE TITLE
[Smoke Test] Settings UI layout is incorrect

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#84]
As title

**Comment by Conjuror** [comment]
https://drive.google.com/a/mozilla.com/file/d/0B11T5xYLeXAOdzRmWkNqbDA1dmc/view?usp=sharing

**Comment by Conjuror** [comment]
Happened on Advan i5C.

Didn't happened on Samsung J7 Prime

**Comment by mTwTm** [comment]
The UI spec has changed after discussion with Carol.

**Comment by Conjuror** [comment]
Closed as verified. double checked on build 471
