### ISSUE TITLE
Fails to use Google OAuth on http://hackmd.io/

### ISSUE THREAD

**Issue by cssjh** [mozilla-tw/Zerda#841]
Google will show this message:

> 403. That’s an error.

> Error: disallowed_useragent

> This user-agent is not permitted to make an OAuth authorization request to Google as it is classified as an embedded user-agent (also known as a web-view). Per our policy, only browsers are permitted to make authorization requests to Google. We offer several libraries and samples for native apps to perform authorization requests in the browser.

**Build:** 1105

**Comment by mTwTm** [comment]
Regression of cf21e7b4 / #510

**Comment by cssjh** [comment]
**Verified** on 1178.
