### ISSUE TITLE
Guessing site title

### ISSUE THREAD

**Issue by cssjh** [mozilla-tw/Zerda#843]
Tried with https://aloodo.org/ test on build **1105**:

![aloodo](https://user-images.githubusercontent.com/8446577/30584160-7e60e3d8-9d5b-11e7-99f9-984ea6d9a7b0.png)

**Comment by cssjh** [comment]
Reference: #624

**Comment by mTwTm** [comment]
It's not working? interesting

**Comment by mTwTm** [comment]
Close in #865

**Comment by cssjh** [comment]
Works fine on https://aloodo.org/ on 1178.
