### ISSUE TITLE
Inconsistent behaviors for browsing websites

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#85]
Consider two situations:

A) While functional buttons (search, home, settings) are on the screen, tap a link of the webpage you are visiting
B) While functional buttons are **not** on the screen, tap a link of the webpage you are visiting

I am assuming all the links we navigate to should have the same behavior, with the new page open and with/without functional buttons. Currently, if previous page is with functional buttons shown, the next page is. Vise versa. I suggest to have a consistent browsing experience.

**Comment by chianger** [comment]
NO FAB now so let's close it.

**Comment by dakaizou** [comment]
Invalid
