### ISSUE TITLE
[Ask] How actually Turbo mode work on Zerda ?

### ISSUE THREAD

**Issue by dikyarga** [mozilla-tw/Zerda#851]
Is Zerda compress the web pages on Zerda server first and then deliver to the browser ?
like Opera Mini did i mean, 

> Opera Mini mode loads webpages on Opera's servers and delivers the juicy content, without all the frills

 [source](http://www.opera.com/help/mini/ios)

Thank you (:

**Comment by harly21** [comment]
Hi Diky,
Nope, we do not have a compression server like Opera, Turbo mode is the same as turning on tracking protection in Focus, it is just that we want to market it from a performance standpoint rather than privacy. Hope that answers your questions :)

**Comment by dikyarga** [comment]
oh I see, very cool! because when I see "Turbo mode" in my mind refer it to Opera mini that compress on there server and it very scary for me :D

thank you for the answer (:

**Comment by chianger** [comment]
We'll provide "learn more" description about the turbo mode function. Hopefully that helps cautious users to understand better.
