### ISSUE TITLE
[Smoke Test] Crash when opening about page

### ISSUE THREAD

**Issue by dakaizou** [mozilla-tw/Zerda#856]
as title

Build: 1124
DuT: Samsung, Advan, Andromax, Oppo

**Comment by dakaizou** [comment]
related to #194

**Comment by mTwTm** [comment]
focusabout: is invalid url

if (url.equals("focusabout:")) {
            loadAbout(view);
}

should come before the throw Exception branch

**Comment by cssjh** [comment]
**Verified** on 1178.
