### ISSUE TITLE
[Smoke Test] FAB appear/disappear incorrectly

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#86]
While scrolling slowly, functional buttons don't appear or disappear accordingly.

Reproduce rate: 50%

**Comment by walkingice** [comment]
note: this behavior is supposed to be effect by this class

https://github.com/mozilla-tw/Zerda/blob/master/app/src/main/java/org/mozilla/focus/widget/FloatingActionButtonBehavior.java

**Comment by Conjuror** [comment]
According to the source code @walkingice provided, I guess we should categorize this into UX issues.

- If a user drag down for a long distance (without release), and drag up a little bit, the button won't dismiss. (vise versa)
- If a user drag down for a long distance (without release) and swipe up, the button won't dismiss.

**Comment by chianger** [comment]
No FAB now let's close it.

**Comment by dakaizou** [comment]
invalid
