### ISSUE TITLE
Data review: Remaining work

### ISSUE THREAD

**Issue by liuche** [mozilla-tw/Zerda#862]
Looking through the data review document here: https://github.com/mozilla-tw/Zerda/wiki/Telemetry

There are just a few things to fix up, so I will list them here:
* All the "readthedocs.io" links are broken - our documentation has moved to firefox-source-docs, so be sure to update these. There are two links (coreping and events)
* Since Zerda uses the same telemetry library as Focus, please include a link to the android-telemetry library under the Event Ping section (which uses the android-telemetry library, I assume)
* Since we're using Adjust, please also add a section about Adjust, and link to the Adjust library (found here: https://github.com/adjust/android_sdk ) - this section can be short, but just include what we're using Adjust for (install tracking, I assume)
* "Search engine name" - is this from a pre-included list? Maybe you can link to that code here.
* "Enable/Disable image blocking" - it should have a "to: true/false" in the extra, right?

The rest of this document looks fine! Please let me know when these changes have been made and I can sign off on data review.

**Comment by liuche** [comment]
Flagging @idiotmax because I think you are working on this.

**Comment by idiotmax** [comment]
Hi @liuche,
I have update the Telemetry document. Would you help to review these changes, please? Thanks.

**Comment by liuche** [comment]
Thanks Max!

A few more nits:
- The documentation links are correct now, but the text they are linking still says "readthedocs.io" - please update the text to say "on firefox-source-docs.mozilla.org"
- The section on Adjust should include a quick description of two things on this wiki page (not just linking to the Fennec Android Adjust docs).

I would include two things in the Adjust section:
1) When does Adjust send a ping (when Rocket/Zerda is opened? When it is installed from the Play Store? or elsewhere if you're not using the Play Store)
2) What is the endpoint that the data is sent to?

Is the format of the Adjust ping the same as Fennec? If so, you can link to that document and say that the Adjust ping parameters are the same.

Other than that the changes look good!

**Comment by idiotmax** [comment]
Hi @liuche,

I just updated the wiki page. Would you help to review these changes, please? Thanks a lot.

**Comment by liuche** [comment]
This looks okay, but a few comments:
- For Adjust, it's a little bit confusing to just link to the Fennec docs, because I assume that the pings are a little different - is there somewhere in the code that you can link to where the Adjust ping is created in the code? If there isn't a single specific place, I'm fine with making a note to add a more detailed Adjust section later, or work with Elvin to make that "Unified Adjust/Telemetry format" documentation.
- #2 from the last time: What is the endpoint that the Adjust data is sent to?
I see you answered #1, when the ping is sent, but I don't see the answer to #2, which endpoint. Also, would be helpful if you could link to the code there too.
- I just noticed that the Adjust section is right above all the Event Ping parameters (Settings, Events, Browsing, etc), so it looks like all of those parameters are being sent with Adjust. Can you swap the sections so that the header for the Event Ping parameters is actually the Event Ping section?

Thanks for the corrections, these are just a few more things that I didn't see addressed - now that I'm done with 57 and uplifts, I'll be very responsive about pushing this through to the end of the review!

**Comment by idiotmax** [comment]
Hi @liuche 
Wiki page updated! Thanks!

**Comment by liuche** [comment]
Thanks for making all the changes.

Giving this data-review+. This document covers the different tools that are being used for data collection on Zerda, and lists the events and parameters that are being collected. There's no personally identifiable data, and all the probes are collecting Type 1 and Type 2 data. Telemetry is opt-out for Zerda.

I'll also comment on and close out the bugzilla bug tracking this: https://bugzilla.mozilla.org/show_bug.cgi?id=1397692

Thanks!
