### ISSUE TITLE
Search field and the keyboard are not disappeared at the same time

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#87]
While search field and the keyboard are shown and we tap the system back key, I assume both the search field and the keyboard should be gone at the same time. Currently, only keyboard is gone and search field will move to the button of screen. Not sure if it's by design.

**Comment by chianger** [comment]
So according to discussion with Jack/Harly/Tori, the UX decision is we'll keep current 2-step behavior for hiding search input. Closing this bug then.

**Comment by chianger** [comment]
So according to discussion with Jack/Harly/Tori, the UX decision is we'll keep current 2-step behavior for hiding search input. Closing this bug then.
