### ISSUE TITLE
url flickers if user leave a page and then visit another page before the first one loads

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/Zerda#875]

**Comment by mTwTm** [comment]
public void onPageStarted(WebView view, String url, Bitmap favicon) {
        Log.e("mTwTm", "onPageStarted : " + url + " | " + view.getUrl());

    public void loadUrl(@NonNull final String url) {
        final IWebView webView = getWebView();
        if (webView != null) {
            if (UrlUtils.isUrl(url)) {
                this.pendingUrl = null; // clear pending url
                webView.loadUrl(url);
                Log.e("mTwTm", "loadUrl : " + url + " | " + webView.getUrl());

09-24 21:40:03.968 24391-24391/org.mozilla.rocket.debug.null E/mTwTm: loadUrl : https://m.youtube.com/ | https://m.youtube.com/
09-24 21:40:04.069 24391-24391/org.mozilla.rocket.debug.null E/mTwTm: onPageStarted : https://m.youtube.com/ | https://m.youtube.com/
09-24 21:40:05.273 24391-24391/org.mozilla.rocket.debug.null E/mTwTm: loadUrl : http://m.tribunnews.com/ | http://m.tribunnews.com/
09-24 21:40:05.426 24391-24391/org.mozilla.rocket.debug.null E/mTwTm: onPageStarted : http://m.tribunnews.com/ | https://m.youtube.com/
09-24 21:40:06.297 24391-24391/org.mozilla.rocket.debug.null E/mTwTm: loadUrl : https://m.facebook.com/ | https://m.facebook.com/
09-24 21:40:06.467 24391-24391/org.mozilla.rocket.debug.null E/mTwTm: onPageStarted : https://m.facebook.com/ | https://m.youtube.com/
09-24 21:40:07.308 24391-24391/org.mozilla.rocket.debug.null E/mTwTm: loadUrl : https://m.tokopedia.com/ | https://m.tokopedia.com/
09-24 21:40:07.449 24391-24391/org.mozilla.rocket.debug.null E/mTwTm: onPageStarted : https://m.tokopedia.com/ | https://m.youtube.com/
09-24 21:40:09.844 24391-24391/org.mozilla.rocket.debug.null E/mTwTm: loadUrl : http://m.liputan6.com/ | http://m.liputan6.com/
09-24 21:40:10.897 24391-24391/org.mozilla.rocket.debug.null E/mTwTm: loadUrl : http://www.kompas.com/ | http://www.kompas.com/
09-24 21:40:11.251 24391-24391/org.mozilla.rocket.debug.null E/mTwTm: onPageStarted : https://m.tokopedia.com/ | http://www.kompas.com/
09-24 21:40:11.276 24391-24391/org.mozilla.rocket.debug.null E/mTwTm: onPageStarted : http://m.liputan6.com/ | https://m.tokopedia.com/
09-24 21:40:11.627 24391-24391/org.mozilla.rocket.debug.null E/mTwTm: onPageStarted : http://www.kompas.com/ | https://m.tokopedia.com/
09-24 21:40:12.046 24391-24391/org.mozilla.rocket.debug.null E/mTwTm: loadUrl : https://m.bukalapak.com/ | https://m.bukalapak.com/
09-24 21:40:12.460 24391-24391/org.mozilla.rocket.debug.null E/mTwTm: onPageStarted : https://m.tokopedia.com/ | https://m.tokopedia.com/
09-24 21:40:12.463 24391-24391/org.mozilla.rocket.debug.null E/mTwTm: onPageStarted : https://m.tokopedia.com/ | https://m.tokopedia.com/
09-24 21:40:12.800 24391-24391/org.mozilla.rocket.debug.null E/mTwTm: onPageStarted : https://m.bukalapak.com/ | https://m.tokopedia.com/
09-24 21:40:13.257 24391-24391/org.mozilla.rocket.debug.null E/mTwTm: loadUrl : https://m.kapanlagi.com/ | https://m.kapanlagi.com/
09-24 21:40:13.611 24391-24391/org.mozilla.rocket.debug.null E/mTwTm: onPageStarted : https://m.kapanlagi.com/ | https://m.tokopedia.com/

I tend to believe the returned url from onPageStarted is more reliable for this purpose.

**Comment by mTwTm** [comment]
Let's explain this more thoroughly.. After  #821, now we only update url in:
1) org.mozilla.focus.fragment.BrowserFragment$2.onPageFinished
and
2) org.mozilla.focus.webkit.FocusWebViewClient$1.run (When main frame request is fired and can be intercepted.)

...while from the log we can see neither of them is reliable...

09-24 21:48:31.503 24759-24759/org.mozilla.rocket.debug.null E/mTwTm: loadUrl : https://m.youtube.com/ | https://m.youtube.com/
09-24 21:48:31.662 24759-24759/org.mozilla.rocket.debug.null E/mTwTm: https://m.youtube.com/ | org.mozilla.focus.webkit.FocusWebViewClient$1.run(FocusWebViewClient.java:72)
09-24 21:48:32.109 24759-24759/org.mozilla.rocket.debug.null E/mTwTm: https://m.youtube.com/ | org.mozilla.focus.fragment.BrowserFragment$2.onPageFinished(BrowserFragment.java:360)
09-24 21:48:32.268 24759-24759/org.mozilla.rocket.debug.null E/mTwTm: https://m.youtube.com/ | org.mozilla.focus.fragment.BrowserFragment$2.onPageFinished(BrowserFragment.java:360)
09-24 21:48:38.077 24759-24759/org.mozilla.rocket.debug.null E/mTwTm: loadUrl : http://m.tribunnews.com/ | http://m.tribunnews.com/
09-24 21:48:38.239 24759-24759/org.mozilla.rocket.debug.null E/mTwTm: http://m.tribunnews.com/ | org.mozilla.focus.webkit.FocusWebViewClient$1.run(FocusWebViewClient.java:72)
09-24 21:48:39.741 24759-24759/org.mozilla.rocket.debug.null E/mTwTm: loadUrl : https://m.facebook.com/ | https://m.facebook.com/
09-24 21:48:39.915 24759-24759/org.mozilla.rocket.debug.null E/mTwTm: https://m.facebook.com/ | org.mozilla.focus.webkit.FocusWebViewClient$1.run(FocusWebViewClient.java:72)
09-24 21:48:40.875 24759-24759/org.mozilla.rocket.debug.null E/mTwTm: loadUrl : https://m.tokopedia.com/ | https://m.tokopedia.com/
09-24 21:48:41.137 24759-24759/org.mozilla.rocket.debug.null E/mTwTm: https://m.tokopedia.com/ | org.mozilla.focus.webkit.FocusWebViewClient$1.run(FocusWebViewClient.java:72)
09-24 21:48:42.129 24759-24759/org.mozilla.rocket.debug.null E/mTwTm: loadUrl : http://m.liputan6.com/ | http://m.liputan6.com/
09-24 21:48:42.294 24759-24759/org.mozilla.rocket.debug.null E/mTwTm: http://m.liputan6.com/ | org.mozilla.focus.webkit.FocusWebViewClient$1.run(FocusWebViewClient.java:72)
09-24 21:48:43.162 24759-24759/org.mozilla.rocket.debug.null E/mTwTm: loadUrl : http://www.kompas.com/ | http://www.kompas.com/
09-24 21:48:44.272 24759-24759/org.mozilla.rocket.debug.null E/mTwTm: loadUrl : https://m.bukalapak.com/ | https://m.bukalapak.com/
09-24 21:48:44.462 24759-24759/org.mozilla.rocket.debug.null E/mTwTm: http://m.tribunnews.com/ | org.mozilla.focus.webkit.FocusWebViewClient$1.run(FocusWebViewClient.java:72)
09-24 21:48:44.464 24759-24759/org.mozilla.rocket.debug.null E/mTwTm: http://m.tribunnews.com/ | org.mozilla.focus.fragment.BrowserFragment$2.onPageFinished(BrowserFragment.java:360)
09-24 21:48:45.348 24759-24759/org.mozilla.rocket.debug.null E/mTwTm: loadUrl : https://m.tokopedia.com/ | https://m.tokopedia.com/
09-24 21:48:45.820 24759-24759/org.mozilla.rocket.debug.null E/mTwTm: http://m.tribunnews.com/ | org.mozilla.focus.fragment.BrowserFragment$2.onPageFinished(BrowserFragment.java:360)
09-24 21:48:45.822 24759-24759/org.mozilla.rocket.debug.null E/mTwTm: http://m.tribunnews.com/ | org.mozilla.focus.webkit.FocusWebViewClient$1.run(FocusWebViewClient.java:72)
09-24 21:48:45.824 24759-24759/org.mozilla.rocket.debug.null E/mTwTm: http://m.tribunnews.com/ | org.mozilla.focus.fragment.BrowserFragment$2.onPageFinished(BrowserFragment.java:360)

This is a nightmare...

**Comment by chianger** [comment]
downgrade to P2 per discussion with UX since this is not as easy to reproduce as before.

**Comment by chianger** [comment]
upgrade to P1 for investigation workaround solution

**Comment by mTwTm** [comment]
Regression of 943b5b3b4

**Comment by dakaizou** [comment]
verified in build 1512
