### ISSUE TITLE
[Smoke Test] Search suggestions don't refresh after switching app

### ISSUE THREAD

**Issue by dakaizou** [mozilla-tw/Zerda#885]
STR:
1. Tap on search bar
2. Type in "moz"
3. Switch to another app and switch back to zerda
4. Delete "moz" and type anything else
![screenshot](https://lh3.googleusercontent.com/-_FbMXTchwnE/WcMe5GCi4tI/AAAAAAAAA6c/fq-AyiDerPYd1A8aJ5uToGngn1jiYJUvACK8BGAs/s512/9249871653059299%253Faccount_id%253D3)

Build: 1158
DuT: Oppo, Samsung

**Comment by cssjh** [comment]
**Verified** on 1178.
