### ISSUE TITLE
Use official icon for Zerda

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#886]
as title

**Comment by fangshih** [comment]
Hey @Ben-YPLai  Here are the icon in different sizes 
https://drive.google.com/open?id=0B1V1eo-I8g3dMk54R2JlZS1WVTg

512x512 Google Store
192x192 xxxhdpi
144x144 xxhdpi 
96x96 xhdpi
72x72 hdpi
48x48 mdpi

Let me know if you need any other assets. Thanks!

**Comment by dakaizou** [comment]
verified in build 1178

**Comment by fangshih** [comment]
@Ben-YPLai , We've made some adjustments on the icon, can you help to replace this new set? Thanks! https://drive.google.com/open?id=0B1V1eo-I8g3dRFM4a0FCNC1fWWs
