### ISSUE TITLE
default search engine to set to Google

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Zerda#888]

**Comment by Conjuror** [comment]
related to #541

**Comment by chianger** [comment]
QAWanted to confirm this. It's supposedly fixed already.

**Comment by dakaizou** [comment]
Looks good on Samsung, Advan, Oppo

**Comment by Conjuror** [comment]
It seems to be a migration issue if you installed previous version before and didn't remove its data completely. If we cannot reproduce it in the following week, suggest to **CLOSE** it as invalid.

**Comment by Conjuror** [comment]
Closed as invalid due to QA cannot reproduce it anymore.
