### ISSUE TITLE
URL in history panel isn't correct

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#893]
Build 1158
DuT: Advan

As title, the URL didn't display correctly

![issue](https://user-images.githubusercontent.com/1625148/30682320-d7f0614a-9edb-11e7-8584-b287c868aac8.png)

**Comment by mTwTm** [comment]
Just to make sure: Are you referring only to the entry with "Yahoo - login"?

**Comment by Conjuror** [comment]
Yes. By experience, the URL with title "Yahoo - login" should display it's whole URL or the longest url as it can with "..." in the end. "https:/..." seems too short for the URL field.

Suggest to P2 this one with high priority if we have bandwidth. The reason is if we didn't polish it, user may feel it's not in a good quality.

**Comment by chianger** [comment]
triage: P1

**Comment by Conjuror** [comment]
STR:

1. Visit yahoo.com
2. Tap on the e-mail icon to login
3. Check Browsing History

**Comment by Conjuror** [comment]
MITO has the same issue

**Comment by dakaizou** [comment]
verified in build 1512
