### ISSUE TITLE
Function integration architecture design

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/Zerda#9]
acceptance criteria: an architecture diagram that clearly defines functional and UI components

**Comment by mTwTm** [comment]
![data2](https://user-images.githubusercontent.com/6755074/28403402-196c8f42-6d57-11e7-8010-1623f92fd48e.png)

This is the first public draft. Will update after review, requirement changes, or blocker discoveries.

Please leave comment in this post whenever you found that we should change the implementation design.

**Comment by mTwTm** [comment]
The architecture is translated into code. A visualization of current implementation is available in #8. This issue will be closed. The diagram is out of synced with current architecture and will be updated only if requested.

**Comment by Conjuror** [comment]
no need QA.
