### ISSUE TITLE
[Compatibility] FAB is over Go To Top button

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#90]
Some websites has a "Go To Top" button to assist user to scroll to the top of a web page. FAB will over the button.

For an example, [Merdeka.com](https://m.merdeka.com/) No. 14 in Top 100 ID sites

**Comment by mTwTm** [comment]
The toast from Wikipedia (when we click the Wikipedia page from top site) is also blocked.

**Comment by chianger** [comment]
No FAB now let's close it.

**Comment by dakaizou** [comment]
Invalid
