### ISSUE TITLE
(RC3) releases for android users who don't use google play or aren't in markets where we release on google play

### ISSUE THREAD

**Issue by rtanglao** [mozilla-tw/Zerda#900]
title says it all: [low priority would be nice] releases (i.e. APKs for sideload) for android users who don't use google play or aren't in markets where we release on google play

just copy the focus android releases? 
i.e.:
https://github.com/mozilla-mobile/focus-android/releases

**Comment by chianger** [comment]
thank you @rtanglao for issuing this. 
We did talk about this and we can probably work on it around Oct9.

**Comment by chianger** [comment]
https://github.com/mozilla-tw/Zerda/releases

**Comment by dakaizou** [comment]
verified
