### ISSUE TITLE
Action Panel UI - Unselected tab color is wrong

### ISSUE THREAD

**Issue by carol-mozilla** [mozilla-tw/Zerda#902]
Unselected tab : Icon and text should be on 20% opacity! (based on visual spec)

**Comment by carol-mozilla** [comment]
![screenshot_20170922-155518](https://user-images.githubusercontent.com/6700296/30734808-5810571c-9faf-11e7-9439-f7210433bca8.png)

**Comment by carol-mozilla** [comment]
![screen shot 2017-09-22 at 3 57 09 pm](https://user-images.githubusercontent.com/6700296/30734834-6d8fa4bc-9faf-11e7-9881-10add2437998.png)
Visual spec

**Comment by cssjh** [comment]
**Close** as dup of meta #628.
