### ISSUE TITLE
Change icon

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#911]
Following up issue #886. Please update the icon:

@Ben-YPLai , We've made some adjustments on the icon, can you help to replace this new set? Thanks! https://drive.google.com/open?id=0B1V1eo-I8g3dRFM4a0FCNC1fWWs

**Comment by Conjuror** [comment]
According to update, we'll have a new logo for Zerda. Therefore, not in a hurry for it. :)

Invalid this issue once we have a new logo.

**Comment by joechengla** [comment]
this can probably be closed once we update the app logo icon?
