### ISSUE TITLE
[Smoke Test] Clear input in search bar doesn't clear the text

### ISSUE THREAD

**Issue by dakaizou** [mozilla-tw/Zerda#967]
STR:
1. Tap on search button
2. Type in any character to generate autocompleted text
3. Tap on the clear input at the right
4. Input selected and clear input button disappear

![screenshot](https://lh3.googleusercontent.com/-8bvtNafvyrI/WcsGQ83IW4I/AAAAAAAABI4/287Hg4Y6B1YJZjGPPwZuE4DlF6X7HcsYACL0BGAYYCw/h1280/6317268261022429245%253Faccount_id%253D1)

It's similar to #610, but the clear input button disappears now.
Related to #837 

Build: 1307
DuT: Oppo, Samsung

**Comment by mTwTm** [comment]
Possibly duplicate to #610

**Comment by mTwTm** [comment]
Duplicate to #610

**Comment by dakaizou** [comment]
verified as dup
