### ISSUE TITLE
[Smoke Test] Some devices' download managers replace the same file automatically

### ISSUE THREAD

**Issue by dakaizou** [mozilla-tw/Zerda#970]
Same STR as #969 :
>1. Download the same image
>2. Open Downloads panel
>3. Check the file name 
>4. Repeat Step 1 to 3

Oppo: Snack bar only appears at the first time, and all the file names would be the same, probably due to the download manager replaces the original file. If that's the case, there should be only one record in the Downloads panel

Build: 1307

**Comment by dakaizou** [comment]
related to #584

**Comment by WeiWW** [comment]
Test on OPPO:

1. Snanckbar not show just at first. I think it's hard to reproduce that  snackbar only show at first time.
2. All the name of files are same that are saved in internal storage and we don't move the file.

**Comment by mTwTm** [comment]
Fixed in #1018, see #1007 for behavior description.
