### ISSUE TITLE
Onboarding page string back to the wrong one

### ISSUE THREAD

**Issue by dakaizou** [mozilla-tw/Zerda#978]
### Wrong
![screenshot](https://lh3.googleusercontent.com/-eGSgV-9tWL4/WcseF24BlCI/AAAAAAAABJk/InV0WZlMzsgodxmbP77xINbgoxDs03bHQCL0BGAYYCw/h854/7124401560862173250%253Faccount_id%253D0)

Check #623 0-2 for the right one

Build: 1307

**Comment by idiotmax** [comment]
Closed by #988

**Comment by dakaizou** [comment]
verified in build 1455
